### ISSUE TITLE
Will Power layer of caffe be supported?

### ISSUE THREAD

**Issue by CptSteven** [rockchip-linux/rknn-toolkit#122]
According to the documentation, POW of tensorflow lite  is supported, which I think functions as power. However rknn-toolkit cannot convert power operator of other frameworks. So my question is, will power operators in frameworks like caffe, onnx, be supported at all,
and when if positive?

**Comment by zen-xingle** [comment]
If you are using RKNN-Toolkit v1.7.0, pow in ONNX model is already supported.

And pow in Pyorch(torch.jit) model will be supported in v1.7.1, which is coming soon. We will consider add pow support for caffe model. 

Thank you for using our devices. It you meet any problem, please feel free to tell us.

**Comment by CptSteven** [comment]
That's very helpful. Thanks
