### ISSUE TITLE
Invalid RKNN format. rknn_query, load_model failed

### ISSUE THREAD

**Issue by AIGirl10** [rockchip-linux/rknn-toolkit#129]
We tried to inference ssd_mobilenet _v1 model with C++ inference on Rk3566 board. But got this error

```sh
Loading model ...
rknn_init ...
I RKNN: set log level to 0
E RKNN: Invalid RKNN format
E RKNN: rknn_query, load_model failed
rknn_init fail! ret=-1
```

Tried to search the error code it said its Model Execution error, but not able to understand why its not working, because same model worked with python inference on ubuntu 16.04.

**Comment by zen-xingle** [comment]
For RK3566, RK3568, RK3588 user, please switch to rknn-toolkit2 for help. Sorry for the inconvenience about the confuse of version.
https://github.com/rockchip-linux/rknn-toolkit2

**Comment by AIGirl10** [comment]
@zen-xingle 

whats the difference ? we are following this repo: https://github.com/rockchip-linux/rknpu2/tree/master/examples/rknn_ssd_demo for model inference on board.

I have also posted same issue in that project: https://github.com/rockchip-linux/rknpu2/issues/7

but I saw that, that project wasn't that active so also posted in this project.

**Comment by AIGirl10** [comment]
@zen-xingle 

sure thanks.
