### ISSUE TITLE
alphapose 模型转换成功，但是rknn推理结果完全不正确，模型未量化

### ISSUE THREAD

**Issue by soloist-v** [rockchip-linux/rknn-toolkit#150]
我将alphapose模型转换为onnx并测试了推理，结果正确地输出了概率图，随后我将onnx转换为rknn进行推理测试，结果rknn的推理结果完全不正确，我仔细看了rknn接口文档并进行了任何可能的尝试都无法解决问题，因此我推测是rknn某些算子存在bug。
这是我的实验代码：https://github.com/soloIife/AlphaPoseOnnx.git
模型：百度云 https://pan.baidu.com/s/1yZFx2P0WL-fYPiIMZ5gZMw 提取码: 4ecn

**Comment by zen-xingle** [comment]
感谢反馈，实验测试是depth2space的底层实现有bug，导致结果出错，我们会在后续版本修复这个bug。

**Comment by DDX1126** [comment]
1.实验的代码其实是fast-pose，alphapose在检测姿态之前还需要用yolov3进行人形检测，不然检测单个的人
2.导出onnx的时候请把input改变一下，你现在的输入是[192,256,3,1]，fast-pose一般是[256,320,3,1]

**Comment by soloIife** [comment]
好的，等更新

**Comment by cndcnd085** [comment]
@zen-xingle   更新了没，现在不能量化，使用不起来，
