### ISSUE TITLE
nanodet导出torch和onnx转rknn均失败 nanodet convert failed

### ISSUE THREAD

**Issue by CaesarG** [rockchip-linux/rknn-toolkit#152]
torch version:1.8.2
onnx version:1.6.0

torch->rknn log:
W Verbose file path is invalid, debug info will not dump to file.
D Using CPPUTILS: True
I Start importing pytorch...
D import clients finished
W Pt model version is 1.6(same as you can check through <netron>), but the installed pytorch is 1.8.2+cu111. This may cause the model to fail to load.
D match input input.185
I Parse prim::Constant at 23
I Parse prim::Constant at 24
I Parse prim::Constant at 25
I Parse prim::Constant at 26
I Parse prim::Constant at 27
I Parse prim::Constant at 28
I Parse prim::ListConstruct at 30
I Parse prim::ListConstruct at 31
I Parse prim::ListConstruct at 32
I Parse prim::ListConstruct at 33
I Parse aten::_convolution at input0.20
D Output shape of layer convolution_at_input0.20_1_1: [[0, 320, 320, 24]]
I Parse prim::Constant at 35
I Parse prim::Constant at 36
I Parse prim::Constant at 37
I Parse prim::Constant at 38
I Parse aten::batch_norm at input.186
D Output shape of layer batchnormalize_at_input.186_2_2: [[0, 320, 320, 24]]
I Parse prim::Constant at 44
I Parse aten::leaky_relu_ at input.187
D Output shape of layer leaky_relu_at_input.187_3_3: [[0, 320, 320, 24]]
I Parse prim::Constant at 46
I Parse prim::Constant at 47
I Parse prim::Constant at 48
I Parse prim::Constant at 49
I Parse prim::ListConstruct at 50
I Parse prim::ListConstruct at 51
I Parse prim::ListConstruct at 52
I Parse prim::ListConstruct at 53
I Parse aten::max_pool2d at input.65
D Output shape of layer max_pooling_at_input.65_4_4: [[0, 160, 160, 24]]
I Parse prim::Constant at 59
I Parse prim::Constant at 60
I Parse prim::Constant at 61
I Parse prim::Constant at 62
I Parse prim::Constant at 63
I Parse prim::Constant at 64
I Parse prim::Constant at 65
I Parse prim::Constant at 73
I Parse prim::Constant at 74
I Parse prim::Constant at 75
I Parse prim::Constant at 76
I Parse prim::Constant at 77
I Parse prim::Constant at 78
I Parse prim::Constant at 79
I Parse prim::ListConstruct at 81
I Parse prim::ListConstruct at 82
I Parse prim::ListConstruct at 83
I Parse prim::ListConstruct at 84
I Parse aten::_convolution at input.66
D Output shape of layer convolution_at_input.66_5_5: [[0, 80, 80, 24]]
I Parse prim::Constant at 86
I Parse prim::Constant at 87
I Parse prim::Constant at 88
I Parse prim::Constant at 89
I Parse aten::batch_norm at input.67
D Output shape of layer batchnormalize_at_input.67_6_6: [[0, 80, 80, 24]]
I Parse prim::Constant at 95
I Parse prim::Constant at 96
I Parse prim::Constant at 97
I Parse prim::Constant at 98
I Parse prim::Constant at 99
I Parse prim::ListConstruct at 101
I Parse prim::ListConstruct at 102
I Parse prim::ListConstruct at 103
I Parse prim::ListConstruct at 104
I Parse aten::_convolution at input.68
D Output shape of layer convolution_at_input.68_7_7: [[0, 80, 80, 88]]
I Parse prim::Constant at 106
I Parse prim::Constant at 107
I Parse prim::Constant at 108
I Parse prim::Constant at 109
I Parse aten::batch_norm at input.69
D Output shape of layer batchnormalize_at_input.69_8_8: [[0, 80, 80, 88]]
I Parse prim::Constant at 115
I Parse aten::leaky_relu_ at 116
D Output shape of layer leaky_relu_at_116_9_9: [[0, 80, 80, 88]]
I Parse prim::Constant at 125
I Parse prim::Constant at 126
I Parse prim::Constant at 127
I Parse prim::Constant at 128
I Parse prim::Constant at 129
I Parse prim::ListConstruct at 131
I Parse prim::ListConstruct at 132
I Parse prim::ListConstruct at 133
I Parse prim::ListConstruct at 134
I Parse aten::_convolution at input.70
D Output shape of layer convolution_at_input.70_10_10: [[0, 160, 160, 88]]
I Parse prim::Constant at 136
I Parse prim::Constant at 137
I Parse prim::Constant at 138
I Parse prim::Constant at 139
I Parse aten::batch_norm at input.71
D Output shape of layer batchnormalize_at_input.71_11_11: [[0, 160, 160, 88]]
I Parse prim::Constant at 145
I Parse aten::leaky_relu_ at input.72
D Output shape of layer leaky_relu_at_input.72_12_12: [[0, 160, 160, 88]]
I Parse prim::Constant at 147
I Parse prim::Constant at 148
I Parse prim::Constant at 149
I Parse prim::Constant at 150
I Parse prim::Constant at 151
I Parse prim::Constant at 152
I Parse prim::Constant at 153
I Parse prim::ListConstruct at 155
I Parse prim::ListConstruct at 156
I Parse prim::ListConstruct at 157
I Parse prim::ListConstruct at 158
I Parse aten::_convolution at input.73
D Output shape of layer convolution_at_input.73_13_13: [[0, 80, 80, 88]]
I Parse prim::Constant at 160
I Parse prim::Constant at 161
I Parse prim::Constant at 162
I Parse prim::Constant at 163
I Parse aten::batch_norm at input.74
D Output shape of layer batchnormalize_at_input.74_14_14: [[0, 80, 80, 88]]
I Parse prim::Constant at 169
I Parse prim::Constant at 170
I Parse prim::Constant at 171
I Parse prim::Constant at 172
I Parse prim::Constant at 173
I Parse prim::ListConstruct at 175
I Parse prim::ListConstruct at 176
I Parse prim::ListConstruct at 177
I Parse prim::ListConstruct at 178
I Parse aten::_convolution at input.75
D Output shape of layer convolution_at_input.75_15_15: [[0, 80, 80, 88]]
I Parse prim::Constant at 180
I Parse prim::Constant at 181
I Parse prim::Constant at 182
I Parse prim::Constant at 183
I Parse aten::batch_norm at input.76
D Output shape of layer batchnormalize_at_input.76_16_16: [[0, 80, 80, 88]]
I Parse prim::Constant at 189
I Parse aten::leaky_relu_ at 190
D Output shape of layer leaky_relu_at_190_17_17: [[0, 80, 80, 88]]
I Parse prim::ListConstruct at 191
I Parse aten::cat at x.11
D Output shape of layer cat_at_x.11_18_18: [[0, 80, 80, 176]]
I Parse aten::size at 193
E Catch exception when loading pytorch model: nanodet.torchscript.pth!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 3985, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.load
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 4156, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.parse_nets
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 3783, in rknn.base.RKNNlib.converter.convert_pytorch_new.PyTorchOpConverter.convert_operators
E   File "rknn/base/RKNNlib/converter/convert_pytorch_new.py", line 2485, in rknn.base.RKNNlib.converter.convert_pytorch_new.PyTorchOpConverter.size
E   File "rknn/base/RKNNlib/RKNNnet.py", line 582, in rknn.base.RKNNlib.RKNNnet.RKNNNet.get_layer_by_out_tensor
E AttributeError: 'numpy.ndarray' object has no attribute 'url'
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

onnx->rknn log:

W Verbose file path is invalid, debug info will not dump to file.
D Using CPPUTILS: True
I Start importing onnx...
W Detect Input node:1325 is dynamic input, the shape info is [0]
W Use the follow command to see more detail and try to fix the dynamic dim
W python -m rknn.bin.freeze_inshape_for_onnx_model -h
E Loading dynamic inputs model is not support, please fix it first
E Catch exception when loading onnx model: nanodet.onnx!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/RK_nn.py", line 141, in rknn.base.RKNNlib.RK_nn.RKnn.load_onnx
E   File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 118, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 68, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.__init__
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 73, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.__init__
E   File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Loading dynamic inputs model is not support, please fix it first
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues

**Comment by zen-xingle** [comment]
附下pt模型我们复现一下

**Comment by CaesarG** [comment]
@zen-xingle 
pth文件不能上传，我发群里吧

**Comment by zen-xingle** [comment]
感谢您的反馈！
Torch的已经定位到问题，内部版本已修复。

目前推荐先用以下代码转出onnx模型，由onnx转为rknn模型，测试可正常转过且fp16的结果经验证是正确的。
```
import torch
model = torch.jit.load('nanodet.torchscript.pth')
in_0 = torch.randn(1,3,416,416)
out_0 = model(in_0)
torch.onnx.export(model, in_0, 'test.onnx', example_outputs = out_0)
```

如无其他问题，可以先关闭该issue，感谢您的支持。

**Comment by CaesarG** [comment]
"Torch的已经定位到问题，内部版本已修复。

目前推荐先用以下代码转出onnx模型，由onnx转为rknn模型，测试可正常转过且fp16的结果经验证是正确的。

import torch
model = torch.jit.load('nanodet.torchscript.pth')
in_0 = torch.randn(1,3,416,416)
out_0 = model(in_0)
torch.onnx.export(model, in_0, 'test.onnx', example_outputs = out_0)"
