### ISSUE TITLE
Faster rcnn 转化失败

### ISSUE THREAD

**Issue by chinafzc** [rockchip-linux/rknn-toolkit#155]
利用mmdetection提供的预训练模型，先转化为onnx成功，利用onnx runtime做推理结果也是正确的，然后将onnx转化为rknn失败，也尝试了其他预训练模型，均在转化NonMaxSuppression处报错。
部分日志：
D Calc tensor Where_2579 (1,)
D Calc tensor Reshape_2581 (1,)
W:tensorflow:From /home/fzc/miniconda3/envs/rockchip/lib/python3.6/site-packages/rknn/api/rknn.py:150: The name tf.enable_eager_execution is deprecated. Please use tf.compat.v1.enable_eager_execution instead.

2022-01-05 09:41:49.068411: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2022-01-05 09:41:49.499663: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3399905000 Hz
2022-01-05 09:41:49.511318: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x557a85a25a80 executing computations on platform Host. Devices:
2022-01-05 09:41:49.511406: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
E Calc node NonMaxSuppression : NonMaxSuppression_1753 output shape fail
E Catch exception when loading onnx model: /home/fzc/Documents/openmmlab/model/mmdetection/faster_rcnn_r50_fpn_1x_coco-person_20201216_175929-d022e227.onnx!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/shape_inference.py", line 65, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.shape_inference.infer_shape
E   File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/ops/nonmaxsuppression.py", line 22, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.ops.nonmaxsuppression.NonMaxSuppression
E TypeError: pad() missing 1 required positional argument: 'mode'
E During handling of the above exception, another exception occurred:
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 118, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 112, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.__init__
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1062, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx._shape_inference
E   File "rknn/base/RKNNlib/onnx_ir/onnx_numpy_backend/shape_inference.py", line 70, in rknn.base.RKNNlib.onnx_ir.onnx_numpy_backend.shape_inference.infer_shape
E   File "rknn/api/rknn_log.py", line 323, in rknn.api.rknn_log.RKNNLog.e
E ValueError: Calc node NonMaxSuppression : NonMaxSuppression_1753 output shape fail
E Please feedback the detailed log file <rknn.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues

转换的onnx模型百度网盘链接：
链接: https://pan.baidu.com/s/1Pk35rdlcVYQz6Zau_DsYjQ 提取码: 4vqv

**Comment by zen-xingle** [comment]
NonMaxSuppression 不支持，算子支持列表可以在doc/op_support.md文件里看到

**Comment by ghost** [comment]
@fang027 I understand that the official response indicated that NonMaxSuppression is not supported. However, I have attempted to solve this problem through other means but have not achieved satisfactory results. I am well aware that this issue dates back two years, so I take the liberty of asking you whether you have found an effective solution subsequently. For instance, have you successfully implemented a similar function in the rknn model through an alternative algorithm, or have you modified the model structure to bypass this unsupported operator?
