### ISSUE TITLE
Can not find libdrm.so

### ISSUE THREAD

**Issue by LS1030** [rockchip-linux/rknn-toolkit#159]
运行平台：TB-RK1808M0

运行代码：
rknn_init(&rknn_ctx, model, model_len, flag);

运行信息：
[RKNN] Can not find libdrm.so
librknn_runtime version 1.7.0 (0bef7b3 build: 2021-08-18 19:51:44 base: 1131)

问题描述：
RK1808M0原来的librknn_runtime version 为 1.5.0，通过sudo apt update-->sudo apt upgrade后升级成1.7后，运行测试代码时出现**[RKNN] Can not find libdrm.so**的问题。
使用locate libdrm.so，输出：
/usr/lib/aarch64-linux-gnu/libdrm.so.2
/usr/lib/aarch64-linux-gnu/libdrm.so.2.4.0

请问如何解决，是否需要重新安装rknn-toolkit-1.7.0？因为要使用C的API，如需重装麻烦告知C版本安装方法，谢谢。

**Comment by zen-xingle** [comment]
RKNN-toolkit-1.7.0与 C_API无关的，这个应该是升级有问题导致的。

由于计算棒是另外一个部门设计的，然后调用了NPU库的相关内容，找不到动态库的问题他们会比较清楚，具体在toybrick论坛问下吧。他们好像不在github上回复。

**Comment by LS1030** [comment]
我新建了一个软链接指向libdrm.so.2.4.0就没有报错了。
``ln -s /usr/lib/aarch64-linux-gnu/libdrm.so.2.4.0 /usr/lib/aarch64-linux-gnu/libdrm.so``
