### ISSUE TITLE
Unable to load SlowFast ONNX model

### ISSUE THREAD

**Issue by MrOCW** [rockchip-linux/rknn-toolkit#165]
[log_feedback_to_the_rknn_toolkit_dev_team.log](https://github.com/rockchip-linux/rknn-toolkit/files/7869427/log_feedback_to_the_rknn_toolkit_dev_team.log)
rknn-toolkit   1.7.1
tensorflow-gpu   1.14.0
torch   1.6.0
onnx   1.6.0

**Comment by zen-xingle** [comment]
Hello,

In log file, it seems that all the tensor in the model has 5 dimensions?  I think rknn-toolkit is not ready for this.
