### ISSUE TITLE
运行rknn_init时，输出Kernel "com.vivantecorp.extension.evis.resize_bilinear_F16toF16_UP" does not exist

### ISSUE THREAD

**Issue by LS1030** [rockchip-linux/rknn-toolkit#166]
运行平台：TB-RK1808M0

运行代码：
rknn_init(&rknn_ctx, model, model_len, RKNN_FLAG_COLLECT_PERF_MASK);

运行信息：
librknn_runtime version 1.7.0 (0bef7b3 build: 2021-08-18 19:51:44 base: 1131)
Kernel "com.vivantecorp.extension.evis.resize_bilinear_F16toF16_UP" does not exist
Kernel "com.vivantecorp.extension.evis.argmax_axis2_F16toI16" does not exist

问题描述：
RK1808M0原来的librknn_runtime version 为 1.5.0，通过sudo apt update-->sudo apt upgrade后升级成1.7后，运行代码时出现以上提示信息。
模型是由ONNX模型转RKNN的，里面用到了Resize和Argmax两个OP。

请问这是否是计算棒的环境出现问题，是否需要重新安装rknn-toolkit-1.7.0？

**Comment by zen-xingle** [comment]
模型是以前转的吗？
有可能需要重新转模型和预编译（如果你之前用了的话）

**Comment by LS1030** [comment]
模型已经重新转，能够成功运行且结果准确，但还是出现同样的错误提示并且运行时间过长，尤其是跑resize和argmax的时候耗时特别长。

运行:
```
rknn_query(rknn_ctx, RKNN_QUERY_PERF_DETAIL, &perf_detail, sizeof(rknn_perf_detail)); 
printf("%s", perf_detail.perf_data);
```
部分输出结果：
| Layer id: | Name:                                                      | Operation id: | Operator:   | Target: | Uid: | Time(us): |
| --------- | ---------------------------------------------------------- | ------------- | ----------- | ------- | ---- | --------- |
| 40        | Conv_Conv_0_1088                                           | 1             | CONVOLUTION | NN      | 1088 | 344       |
| 9         | com.vivantecorp.extension.evis.resize_bilinear_F16toF16_UP | 0             | unknown     | SH      | -1   | 2783      |
| 38        | com.vivantecorp.extension.evis.resize_bilinear_F16toF16_UP | 0             | unknown     | SH      | -1   | 6258      |
| 39        | ArgMax_ArgMax_0_1                                          | 0             | unknown     | SH      | 1    | 1657      |

现已尝试使用多个模型，不同模型能跑出相对准确的结果，但均会出现**错误提示**和**耗时过长**的问题。
错误提示均为``Kernel "com.vivantecorp.extension.evis.xxx" does not exist``的格式，曾出现有：
*  com.vivantecorp.extension.evis.resize_bilinear_F16toF16_UP
* com.vivantecorp.extension.evis.resize_bilinear_U8toU8_UP_opt
* com.vivantecorp.extension.evis.resize_bilinear_U8toU8_SAME_2x_upsample_half_pixel_centers
* com.vivantecorp.extension.evis.resize_bilinear_U8toU8_SAME_4x_upsample_half_pixel_centers
* com.vivantecorp.extension.evis.argmax_axis2_F16toI16

这是一个正常的现象还是rknn的bug？需要进行哪方面的处理来解决？

**Comment by zen-xingle** [comment]
resize和argmax这个耗时应该是正常的。如果模型推理结果正确，可以忽略错误提示。

不同算子使用的硬件不同，NN和SH都是NPU里面的单元，但是有性能差异。
Conv是走NN单元的，性能最优，所以速度很快。其他两个算子是走SH单元，性能会差一些。
这也是为什么之前有的模型(如yolov5)建议不要包含后处理，因为大部分后处理算子都无法使用NN单元加速。
