### ISSUE TITLE
c++ api samples

### ISSUE THREAD

**Issue by EhsanVahab** [rockchip-linux/rknn-toolkit#167]
Hi dear
I'm a c++ programmer and very interested to code with rknn and RK3399ProC.
is there any repository (like current with python language) for rknn with c++ api ?

**Comment by zen-xingle** [comment]
For RK3399pro, the c++ api samples is here.
https://github.com/rockchip-linux/RKNPUTools/tree/rk33/mid/8.1/develop/rknn-api/Linux/rknn_api_sdk

**Comment by EhsanVahab** [comment]
Thanks a lot Zen
