### ISSUE TITLE
Init Runtime Fails with RKNN_ERR_DEVICE_UNAVAILABLE

### ISSUE THREAD

**Issue by gitbatu** [rockchip-linux/rknn-toolkit#174]
Hello, 

Trying to run the mobilenet_v1 example in rknn toolkit 1.7.1. Path to the file is: rknn-toolkit-1.7.1/examples/tflite/mobilenet_v1/test.py

My device is RV1126. I set the rknn.config:
`rknn.config(mean_values=[[127.5, 127.5, 127.5]], std_values=[[127.5, 127.5, 127.5]], reorder_channel='0 1 2', target_platform=['rv1126'])`
And added target platform to the init_runtime:
`    ret = rknn.init_runtime(target='rv1126', device_id='179e8563de15b86a')
`

I get the following error when I run the test.py:
```
  E Catch exception when init runtime!
  E Traceback (most recent call last):
  E   File "rknn/api/rknn_base.py", line 897, in rknn.api.rknn_base.RKNNBase.init_runtime
  E   File "rknn/api/rknn_runtime.py", line 341, in rknn.api.rknn_runtime.RKNNRuntime.build_graph
  E Exception: RKNN init failed. error code: RKNN_ERR_DEVICE_UNAVAILABLE
  E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
  E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
  E Current device id is: 179e8563de15b86a
  E Devices connected:
  E ['179e8563de15b86a']
```
  Init runtime environment failed

What should I do?

Thanks.

**Comment by zen-xingle** [comment]
Hello,

You can try to figure it out refer to this doc https://github.com/rockchip-linux/rknn-toolkit/blob/master/doc/Rockchip_Trouble_Shooting_RKNN_Toolkit_V1.7.1_EN.pdf, Chapter 4.

If you driver on devices is too old, you can update it from here. https://github.com/rockchip-linux/rknpu.
`cat /usr/lib/librknn_runtime.so | grep version` on board and the driver version will be printed.

**Comment by gitbatu** [comment]
Hi! 

Thanks for pointing it out. I have updated the rknpu drivers but the error is still there. Here are the current version information for the drivers:
lbrknn_runtime.so:
`[root@RV1126_RV1109:/]# strings /usr/lib/librknn_runtime.so | grep version`
`librknn_runtime version 1.7.1 (97198ce build: 2021-11-24 09:32:17 base: 1131)
`
rknn_server:
`[root@RV1126_RV1109:/]# strings /usr/bin/rknn_server | grep build`
`1.7.1 (0cfd4a1 build: 2021-11-24 09:33:04)
`
NPU driver:
`[root@RV1126_RV1109:/]# dmesg | grep -i "Galcore version"`
`[    1.001759] Galcore version 6.4.6.5.351518
`

The "RKNN_ERR_DEVICE_UNAVAILABLE" problem persists. However I have not done any builds or anything for updating the drivers. I have just used the adb push command to place the files inside the device. Should I have done anything else?

Thanks.

**Comment by zen-xingle** [comment]
Hello, 

Maybe the problem is that ntb function is not enable.

`vi /etc/init.d/.usb_config` and there should have code like 
`usb_ntb_en`
`usb_adb_en`
either one of them is not exists, add it manually

**Comment by gitbatu** [comment]
Hello,

Indeed usb_ntb_en was missing in config. I have added it, however, that caused the device to be undetected by "adb" (using "adb devices" command.). Any more ideas?

Thanks.

**Comment by gitbatu** [comment]
Hi,

It turns out that I needed to set read/write permissions to the device by executing the update_rk1808_usb_rule.sh script. The examples work now. Thanks for your help.

**Comment by zen-xingle** [comment]
Hello,

Sorry, I haven't meet such case. Maybe you can try to reboot pc and npu_device both?

**Comment by gitbatu** [comment]
Hello,

I wonder if I did the driver update correctly. Let me summarize what I did and maybe you could help me fix it:
- Used adb push command to place the "linux-armhf-puma" folder to the root directory o my RV1126,
- Moved the /linux-armhf-puma/usr/lib/* to /usr/lib/ inside RV1126,
- Moved /linux-armhf-puma/usr/bin/rknn_server to /usr/bin/ insdie RV1126,
- Used adb push command to place the "galcore_puma.ko" file to RV1126 as /lib/modules/galcore.ko,
- Rebooted RV1126
Are these the correct steps to follow?

Thank you.

**Comment by gitbatu** [comment]
Hello,

Update: This problem does not show up when I use the BoarConfig.mk file for build configuration and the toolkit works on NPU. I still don't know what the issue is with the  BoarConfig-facial_gate.mk which was already loaded on my device at the time of purchasing.

**Comment by wh9** [comment]
Hello,

After I run `rknn_server` with the ` start_rknn.sh` script, I can connect normally.
The `boarconfig. mk` file uses the NPU full driver by default, so the `start_rknn.sh` is run on line 31 (`start_rknn.sh &`) of the `/etc/init.d/S60NPU_init` file on the board.
The `boarconfig-facial_gate. mk` file uses the NPU min driver by default, if you later use the `adb` command to replace the NPU mini driver with the NPU full driver, You need to uncomment line 31 (`# start_rknn.sh &`) in the `/etc/init.d/S05NPU_init` file to ensure that the `rknn_server` starts on the board.

**Comment by gitbatu** [comment]
Hello wh9, thank you so much for your help. It works now. So the problem was rknn_server being inactive.

**Comment by starhou** [comment]
> 你好，
> 
> `rknn_server`使用` start_rknn.sh`脚本运行后，我可以正常连接。 该`BoarConfig.mk`文件默认使用 NPU 全驱动，所以在板子上文件的`start_rknn.sh`第 31 行 ( `start_rknn.sh &`)运行。 该文件默认使用 NPU min 驱动，如果以后使用命令将 NPU mini 驱动替换为 NPU full 驱动，需要取消文件中第 31 行的注释（`/etc/init.d/S60NPU_init``BoarConfig-facial_gate.mk``adb``# start_rknn.sh &``/etc/init.d/S05NPU_init``rknn_server`

@gitbatu  where is start_rknn.sh? I can't find it.

**Comment by gitbatu** [comment]
@starhou the shell script itself is in this path:
`rknpu/drivers/common/usr/bin/start_rknn.sh`

If you want to know where the init file is:
`rknpu/drivers/common/etc/init.d/S60NPU_init`

Hope this helps.

**Comment by nicklezheng** [comment]
> Hello,
> 
> Indeed usb_ntb_en was missing in config. I have added it, however, that caused the device to be undetected by "adb" (using "adb devices" command.). Any more ideas?
> 
> Thanks.

I meet the same problem, how did you fix it?
