### ISSUE TITLE
RKNN Model Zoo

### ISSUE THREAD

**Issue by EhsanVahab** [rockchip-linux/rknn-toolkit#178]
Hi friends.
Do you know whether there is any model zoo or converted model for RKNN or not?
for example **yolov3.rknn**

**Comment by zen-xingle** [comment]
Hello!
1.For yolov3, it's converted from darknet model, trained by using https://github.com/pjreddie/darknet.
2.Yeah, we had got a plan to push a respository, aiming to claim how to train/test/eval/deploy the common model on rknn-devices. The yolov5 would be the first one to support. It's supposed to come out in the middle of this month.

**Comment by EhsanVahab** [comment]
> Hello! 1.For yolov3, it's converted from darknet model, trained by using https://github.com/pjreddie/darknet. 2.Yeah, we had got a plan to push a respository, aiming to claim how to train/test/eval/deploy the common model on rknn-devices. The yolov5 would be the first one to support. It's supposed to come out in the middle of this month.

we will be very thankful dear @zen-xingle 

I have another idea and deeply appreciate if you consider.
unfortunately there is no straightforward document to run the models with **NPU** on **_development board_**. 
for example at first I thought installing the RKNN_Toolkit is enough to use NPU but spent two days to know the driver plays an important role.
I'm just wondering would it be possible to enrich the **Installation part** of **User Guide's document** for beginners and help the users step by step after OS installation?

**Comment by zen-xingle** [comment]
Sorry for the confusion in using RKNN devices.  The new respository will also contains the deployment code as C++ demo. And the EN doc will also be updating.

For driver,
1.The driver is deeply binded to the system, meaning that different **third party development boards** may got **imcompatible.** And the best way is to ask the seller(third party) for updating driver.
2.If you are using **development board mamufactured directly from RK**, updating driver version(for rk1808/rv1109/rv1126) refer to here https://github.com/rockchip-linux/rknpu.

For **deployment example**, refer to here https://github.com/rockchip-linux/rknpu/tree/master/rknn/rknn_api/examples. This should work well with all boards.

**Comment by EhsanVahab** [comment]
> Sorry for the confusion in using RKNN devices. The new respository will also contains the deployment code as C++ demo. And the EN doc will also be updating.
> 
> For driver, 1.The driver is deeply binded to the system, meaning that different **third party development boards** may got **imcompatible.** And the best way is to ask the seller(third party) for updating driver. 2.If you are using **development board mamufactured directly from RK**, updating driver version(for rk1808/rv1109/rv1126) refer to here https://github.com/rockchip-linux/rknpu.
> 
> For **deployment example**, refer to here https://github.com/rockchip-linux/rknpu/tree/master/rknn/rknn_api/examples. This should work well with all boards.

thanks for for your responsibility to answer the comments. your comment for the driver installation would be very worthy. 
we are being on watch to get updated document and C++ api
