### ISSUE TITLE
when i run the yolov5 example find some error

### ISSUE THREAD

**Issue by erquren** [rockchip-linux/rknn-toolkit#184]
[log_feedback_to_the_rknn_toolkit_dev_team.log](https://github.com/rockchip-linux/rknn-toolkit/files/8030862/log_feedback_to_the_rknn_toolkit_dev_team.log)

this is my log
and any thing should i support?
how to run this example

**Comment by zen-xingle** [comment]
Would you mind trying rknn_toolkit_lite(https://github.com/rockchip-linux/rknn-toolkit/tree/master/rknn-toolkit-lite/packages)? Because on RK3399pro environment, memory is limited and the log show that there is a memory shortcut error.
