### ISSUE TITLE
[YOLOv4] Darknet Mish Activation "ignored"

### ISSUE THREAD

**Issue by danmartzla** [rockchip-linux/rknn-toolkit#19]
Hi RKNN team,

I've recently tried to load and convert the official YOLOv4 model in Darknet format by using the RKNN Toolkit 1.3.2.  The model is quite new so I supposed it would not work; but surprisingly, the RKNN Toolkit did not complain anytime even in verbose mode. After a successful .RKNN conversion, an inference simulation was done taking as reference the YOLOv3 provided example. However, the output results from the YOLOv4 model were not consistent.

The YOLOv4 model uses the MISH activation ([https://arxiv.org/abs/1908.08681]) which I supposed it was not supported by the latest RKNN-Toolkit. After changing all the MISH activations to "Leaky" (as in YOLOv3), the YOLOv4 model worked.

It is normal that the RKNN-Toolkit will not warn the developers that there are "unsupported functions" when loading models?

By the way, it would be nice to have the MISH function supported in the following RKNN-Toolkit updates which generally gives better accuracy as shown in the literature.

Best,

**Comment by scangit** [comment]
The mish activation function will be supported in the next release. Probably in August. If you are an official customer, you can now apply for the trial version via https://redmine.rockchip.com.cn/.
