### ISSUE TITLE
mmaction2 的 pytorch 模型转为 torchscript 后转rknn 失败

### ISSUE THREAD

**Issue by hjwangu** [rockchip-linux/rknn-toolkit#194]
mmaction2 的 configs/recognition/tsm/tsm_r50_video_inference_1x1x8_100e_kinetics400_rgb.py   checkpoints/tsm_r50_video_1x1x8_100e_kinetics400_rgb_20200702-a77f4328.pth
模型转为torchscript 后 转rknn 报如下错,估计是却算子,但也看不出缺啥算子,如何解决?

D Using CPPUTILS: True
I Start importing pytorch...
D import clients finished
W Pt model version is 1.6(same as you can check through <netron>), but the installed pytorch is 1.8.1+cpu. This may cause the model to fail to load.
D match input imgs.1
I Parse prim::Constant at 2
I Parse prim::Constant at 3
I Parse prim::Constant at 4
I Parse prim::Constant at 5
I Parse prim::Constant at 6
I Parse prim::Constant at 7
I Parse aten::size at 10
I Parse prim::NumToTensor at other.1
I Parse aten::size at 12
I Parse prim::NumToTensor at 13
I Parse aten::Int at 14
I Parse aten::size at 15
I Parse prim::NumToTensor at 16
I Parse aten::Int at 17
I Parse aten::size at 18
E Catch exception when loading pytorch model: test.pt!
E Traceback (most recent call last):
E   File "rknn\base\RKNNlib\app\importer\import_pytorch.py", line 129, in rknn.base.RKNNlib.app.importer.import_pytorch.ImportPytorch.run
E   File "rknn\base\RKNNlib\converter\convert_pytorch_new.py", line 3985, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.load
E   File "rknn\base\RKNNlib\converter\convert_pytorch_new.py", line 4156, in rknn.base.RKNNlib.converter.convert_pytorch_new.convert_pytorch.parse_nets
E   File "rknn\base\RKNNlib\converter\convert_pytorch_new.py", line 3783, in rknn.base.RKNNlib.converter.convert_pytorch_new.PyTorchOpConverter.convert_operators
E   File "rknn\base\RKNNlib\converter\convert_pytorch_new.py", line 2499, in rknn.base.RKNNlib.converter.convert_pytorch_new.PyTorchOpConverter.size
E IndexError: list index out of range
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.

**Comment by zen-xingle** [comment]
你好，
看起来是size算子出错了，具体问题需要上传模型我们这边看下；绕过的话，可能是算子里面有些自动根据shape计算的操作导致的，可以把依赖前面shape的参数根据输入改成固定参数试试。

**Comment by hjwangu** [comment]
模型文件从哪上传?  没找见上传的地方.  
我把模型问文件的压缩文件zip格式拖到回复框里,提示 is not included in the list

**Comment by hjwangu** [comment]
> 模型文件从哪上传? 没找见上传的地方. 我把模型问文件的压缩文件zip格式拖到回复框里,提示 is not included in the list

应该是模型文件太大了

**Comment by hjwangu** [comment]
链接：https://pan.baidu.com/s/1qdXqJxV54tK_KM25UBhq1A 
提取码：mcn3 
模型文件放到百度网盘了,帮忙给看看啥问题,多谢!

**Comment by hjwangu** [comment]
> 链接：https://pan.baidu.com/s/1qdXqJxV54tK_KM25UBhq1A
> 提取码：mcn3
> 模型文件放到百度网盘了,帮忙给看看啥问题,多谢!

**Comment by hjwangu** [comment]
模型文件见附件 ,帮忙看看问题谢谢!----- 原始邮件 -----
发件人：nπ ***@***.***>
收件人：rockchip-linux/rknn-toolkit ***@***.***>
抄送人：hjwangu ***@***.***>,  Author ***@***.***>
主题：Re:_[rockchip-linux/rknn-toolkit]_mmaction2_的_pytorch_模型转为_torchscript_后转rknn_失败_(Issue_#194)
日期：2022年02月22日 15点18分



你好，


看起来是size算子出错了，具体问题需要上传模型我们这边看下；绕过的话，可能是算子里面有些自动根据shape计算的操作导致的，可以把依赖前面shape的参数根据输入改成固定参数试试。



—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
