### ISSUE TITLE
Failed to installing the dependencies by following the doc

### ISSUE THREAD

**Issue by shaojun** [rockchip-linux/rknn-toolkit#202]
I'm using Ubuntu 20.04.3 LTS, x64, RTX3090.
`miniconda` as virtual env tool for python.

By following the doc: _Rockchip_User_Guide_RKNN_Toolkit_V1.7.1_CN.pdf_  I got several errors when installing the dependencies:

my python environment:

> (rknntoolkit) shao@yaoming:~$ python3
> Python 3.5.6 |Anaconda, Inc.| (default, Jun  4 2021, 13:57:47) 
> [GCC 7.5.0] on linux

Install tensorflow-gpu==1.14.0 error:

> pip3 install tensorflow-gpu==1.14.0
> Defaulting to user installation because normal site-packages is not writeable
> Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
> **ERROR: Could not find a version that satisfies** the requirement tensorflow-gpu==1.14.0 (from versions: 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.8.0rc0, 2.8.0rc1, 2.8.0)
> ERROR: No matching distribution found for tensorflow-gpu==1.14.0
> 
> 

Install torchvision==0.4.0 error:
> 
> pip3 install torch==1.5.1 torchvision==0.4.0
> Defaulting to user installation because normal site-packages is not writeable
> Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
> Collecting torch==1.5.1
>   Downloading torch-1.5.1-cp38-cp38-manylinux1_x86_64.whl (753.2 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 753.2/753.2 MB 5.8 MB/s eta 0:00:00
> ERROR: Could not find a version that satisfies the requirement torchvision==0.4.0 (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.11.1, 0.11.2, 0.11.3)
> ERROR: No matching distribution found for torchvision==0.4.0

Are those old versions necessary, or may the doc need get update?

Install _rknn_toolkit-1.7.1-cp35-cp35m-linux_x86_64.whl_  error:

> 
> (rknntoolkit) shao@yaoming:~$ pip3 install ~/Downloads/rknn-toolkit-v1.7.1-packages/packages/rknn_toolkit-1.7.1-cp35-cp35m-linux_x86_64.whl 
> Defaulting to user installation because normal site-packages is not writeable
> Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
> ERROR: rknn_toolkit-1.7.1-cp35-cp35m-linux_x86_64.whl is not a supported wheel on this platform.

also, tried this:

`python -m pip install tensorflow==1.14.0`
got error:

> Exception:
> Traceback (most recent call last):
>   File "/home/shao/miniconda3/envs/rknntoolkit/lib/python3.5/site-packages/pip/_internal/basecommand.py", line 228, in main
>     status = self.run(options, args)
>   File "/home/shao/miniconda3/envs/rknntoolkit/lib/python3.5/site-packages/pip/_internal/commands/install.py", line 241, in run
>     with self._build_session(options) as session:
>   File "/home/shao/miniconda3/envs/rknntoolkit/lib/python3.5/site-packages/pip/_internal/basecommand.py", line 78, in _build_session
>     if options.cache_dir else None
>   File "/home/shao/miniconda3/envs/rknntoolkit/lib/python3.5/posixpath.py", line 89, in join
>     genericpath._check_arg_types('join', a, *p)
>   File "/home/shao/miniconda3/envs/rknntoolkit/lib/python3.5/genericpath.py", line 143, in _check_arg_types
>     (funcname, s.__class__.__name__)) from None
> TypeError: join() argument must be str or bytes, not 'int'

could you help to check?

**Comment by gitbatu** [comment]
Hi! What conclusion was arrived at regarding this issue?

**Comment by gitbatu** [comment]
Hi, did you manage to build the SDK?

**Comment by shaojun** [comment]
> Hi, did you manage to build the SDK?

i re-create a `python3.6` env, and change the version of that two to below to made success:

`pip3 install torch==1.4.0 torchvision==0.5.0`

**Comment by gitbatu** [comment]
Great! Thank you.
