### ISSUE TITLE
[Darknet] Conversion fails for Image classification models

### ISSUE THREAD

**Issue by danmartzla** [rockchip-linux/rknn-toolkit#21]
Hello Rockchip team,

I have been experiencing an issue converting Darknet models. YOLO-based models are successfully converted, however, the problem comes when converting image classification models (ex: Darknet-59, MobileNet-v2, ResNet, ...). 

The problem shows up when using any ImageNet pre-trained models; for example, Cross Stage Partial Networks and others available [here](https://github.com/WongKinYiu/CrossStagePartialNetworks).

The models (.cfg) and the weights (.weights) are downloaded and used without any additional training or modification. These models work perfectly when executed with the [original Darknet framework](https://github.com/AlexeyAB/darknet) by Alexey.

The RKNN-Toolkit debug/error output looks always the same (size and shape may vary regarding the model):

`...`
`D Process output_156 ...`
`D RKNN output shape(output): (0 1 1 1000)`
`I Build test complete.`
`E Catch exception when loading darknet model: ./test.cfg!`
`E Traceback (most recent call last):`
`E   File "rknn/api/rknn_base.py", line 555, in rknn.api.rknn_base.RKNNBase.load_darknet`
`E   File "rknn/base/RKNNlib/converter/convert_darknet.py", line 685, in` `rknn.base.RKNNlib.converter.convert_darknet.Converter.load_blobs`
`E   File "rknn/base/RKNNlib/converter/convert_darknet.py", line 403, in` `rknn.base.RKNNlib.converter.convert_darknet.Convolution_Blob_Assign.assign`
`E   File "<__array_function__ internals>", line 6, in reshape`
`E   File "/home/dxxx/.virtualenvs/python3.6/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 299, in reshape`
`E     return _wrapfunc(a, 'reshape', newshape, order=order)`
`E   File "/home/dxxx/.virtualenvs/python3.6/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc`
`E     return bound(*args, **kwds)`
`E ValueError: cannot reshape array of size 598984 into shape (384,384,3,3)`

It looks like the problem appears when loading the weights into the model but there is no way to fix this from the RKNN-Toolkit 1.3.2 interface. All dependencies are installed and their versions match as specified in RKNN-Toolkit User Guide 1.3.2 document.

Thanks.

**Comment by EhsanVahab** [comment]
I know it is too late to answer but I comment for others with same problem.
use the latest rknn_toolkit 1.7.1 to convert Alexyab 's yolo models. it works pretty well.
then in order to inference, use the yolov5 samples on onnx directory.
