### ISSUE TITLE
YOLOV5 ONNX have diffrent output shape from the example

### ISSUE THREAD

**Issue by serkanpeldek** [rockchip-linux/rknn-toolkit#225]
Hi 

I'm trying to do onnx->rknn onversion for the yolov5 model. but when I convert the model to onnx format, the output layer is different in the yolov5s.onnx model located at https://github.com/rockchip-linux/rknn-toolkit/tree/master/examples/onnx/yolov5. This causes me to get an error in the inference processes in the test.py file.

For example, the file in the repo is yolov5s.onnx and the file I am working with is costum.onnx. The output layers are as follows.

yolov5s.onnx :
![yolov5s_onnx_output](https://user-images.githubusercontent.com/8057652/162894987-03d85807-0b6b-4e61-95d1-e25740c32966.png)

costum.onnx:
![costum_onnx_output](https://user-images.githubusercontent.com/8057652/162895042-b3953543-e0fd-418c-bda3-50c6881b33ab.png)

How can I get an ONNX model with outputs like in [the example]( https://github.com/rockchip-linux/rknn-toolkit/tree/master/examples/onnx/yolov5)?
or
How can I make the output of my ONNX model suitable for yolov5 post_process operations?

Any help with the rknn conversion of the yolov5 model would be greatly appreciated.

Best Regards

**Comment by shaojun** [comment]
hi, I'm using _yolov5s_ model, the output name which passed into:

`ret = rknn.load_onnx(model=ONNX_MODEL,outputs=['onnx::Reshape_nnn', 'onnx::Reshape_nnn', 'onnx::Reshape_nn'])`

should from these 3 Conv node in Netron node tree:

![image](https://user-images.githubusercontent.com/3241829/164147810-2234b3bf-b3b5-4d43-aac1-d2fc92c751c1.png)

**Comment by serkanpeldek** [comment]
@shaojun 
Thank you very much. Your comment helped me to realize my mistake. I finally convert onnx->rknn correctly.

To clarify I want to explain my solution:
What ever the shape of custom model outputs, like mine in the first comment, it is enough to pass names of the last three Conv  to the function
ret = rknn.load_onnx(model=ONNX_MODEL,outputs=[...])

last three Convs:
![lass_three_convs](https://user-images.githubusercontent.com/8057652/164165291-e305898d-45c1-4ab3-954b-1a40c407b5ef.png)

Conv 1:
![conv1_outputs](https://user-images.githubusercontent.com/8057652/164165802-f6a3c4dd-bd67-4fe1-9d4d-10fa340a19d4.png)

Conv2:
![conv2_outputs](https://user-images.githubusercontent.com/8057652/164165843-71380796-adfb-4f21-9f63-2133a8351557.png)

Conv3:
![conv3_outputs](https://user-images.githubusercontent.com/8057652/164165870-8ecb0e00-813f-4568-b45f-267cc1835ca4.png)

Finaly the function parameters are:
ret = rknn.load_onnx(model=ONNX_MODEL,outputs=["onnx::Reshape_326", "onnx::Reshape_364", "onnx::Reshape_402"])

I hope explanations help others to not lost hours or days because of lack of explanations.

**Comment by shaojun** [comment]
there's a group chat tools that called _QQ_ (was popular in china), the team is using that for dissussion:
![image](https://user-images.githubusercontent.com/3241829/164167366-735537ae-dee5-4168-a8d0-8782226d59c6.png)

**Comment by serkanpeldek** [comment]
Solved

**Comment by shaojun** [comment]
@serkanpeldek I'm told that the model training and convert (to `.rknn` format) should follow this repo's steps: [rknn_model_zoo - yolov5](https://github.com/airockchip/rknn_model_zoo/tree/main/models/vision/object_detection/yolov5-pytorch) which obviously much simpler and also model anchors are output as well, thus the `rknntoolkit` seems not necessary anymore for model conversion.
But I have not got time to try yet, maybe next week.

**Comment by serkanpeldek** [comment]
> @shaojun I figured out yolov5. Thanks again.
I am struggle with sklearn to ron conversion. I openned an issue [here](https://github.com/rockchip-linux/rknn-toolkit/issues/247#issue-1245031967)

Any feedback or comments about the conversion sklearn to rknn are welcomed.
