### ISSUE TITLE
Load .onnx yolov5s model got error KeyError: '378'

### ISSUE THREAD

**Issue by shaojun** [rockchip-linux/rknn-toolkit#232]
我操作的步骤完全参考于：
https://github.com/rockchip-linux/rknn-toolkit/tree/master/examples/onnx/yolov5

1. 创建`conda env` with `python3.7`
_activate_ 此 _env_, 同时安装python dependencies by `pip3 install -r requirements.txt`.
2. [clone yolov5](https://github.com/ultralytics/yolov5/) 并依RKNN文档DEMO时的版本check out到此commit id上:

    > 使用yolov5官方仓库导出模型，链接：[https://github.com/ultralytics/yolov5。该demo创建时yolov5的最新节点的commit](https://github.com/ultralytics/yolov5%E3%80%82%E8%AF%A5demo%E5%88%9B%E5%BB%BA%E6%97%B6yolov5%E7%9A%84%E6%9C%80%E6%96%B0%E8%8A%82%E7%82%B9%E7%9A%84commit) id为:c5360f6e7009eb4d05f14d1cc9dae0963e949213
    并在私有数据集上训练了模型，通过detect.py一切正常。

3. 安装 _onnx==1.6.0_  (原因是rknn toolkit中用的是此版本的 _onnx_ ), 并执行了`export`转`.pt`转至`.onnx`.
    ```
    pip3 list |grep onnx
    onnx                    1.6.0
    ```

    虽然最后_.onnx_生成了。但同时export过程中可以**看到有个**`failure`：
    
    > PyTorch: starting from runs/train/exp/weights/last.pt (14.5 MB)
    > 
    > TorchScript: starting export with torch 1.11.0+cu102...
    > ...
    > ...
    > ONNX: starting export with onnx 1.6.0...
    > ...
    > ONNX: export **failure**: Your model ir_version is higher than the checker's.
    > Torch version 1.11.0+cu102 has not been tested with coremltools. You may run into unexpected errors. Torch 1.10.2 is the most recent version that has been tested.
    > 
    > CoreML: starting export with coremltools 5.2.0...
    > ...
    > ...
    
    不管它(一会再尝试用最新版本的onnx)，现仍将生成的`.onnx`拷贝至`example/onnx/yolov5/`下.

4. 换到rknn toolkit的`conda env`:

    执行python3 test.py时，得到以下错误：
    
    > W Call onnx.optimizer.optimize fail, skip optimize
    > W Please confirm that your onnx opset_version <= 11 (current opset_verison = 12)!!!
    > E Catch exception when loading onnx model: elenet_yolov5s.onnx!
    > E Traceback (most recent call last):
    > E   File "rknn/base/RKNNlib/RK_nn.py", line 141, in rknn.base.RKNNlib.RK_nn.RKnn.load_onnx
    > E   File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 118, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
    > E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 111, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.__init__
    > E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1059, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx._build_subgraph
    > E   File "rknn/base/RKNNlib/converter/onnx_util.py", line 366, in rknn.base.RKNNlib.converter.onnx_util.onnx_subgraph.build_subgraph
    > E KeyError: '378'
    > E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
    > E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
    > Load yolov5 failed!
    > 

5. 尝试在`export yolov5`时使用最新的onnx， 即版本1.11.0， 则`export`无错：
    
    > ONNX: starting export with onnx 1.11.0...
    > /home/shao/yolov5/models/yolo.py:58: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
    >   if self.grid[i].shape[2:4] != x[i].shape[2:4] or self.onnx_dynamic:
    > ONNX: export success, saved as runs/train/exp/weights/last.onnx (28.4 MB)
    > ONNX: run --dynamic ONNX model inference with: 'python detect.py --weights runs/train/exp/weights/last.onnx'
    > Torch version 1.11.0+cu102 has not been tested with coremltools. You may run into unexpected errors. Torch 1.10.2 is the most recent version that has been tested.
    > ...
    > ...
    
    但在rknn中执行 python3 test.py, 同样的错误。

Questions:
1. 以上错误如何避免呢?
2. 在yolov5的repo下训练后，需要使用什么版本的`onnx`来做`export`呢？_1.6.0_ or _1.11.0_?

**Comment by serkanpeldek** [comment]
> 我操作的步骤完全参考于： https://github.com/rockchip-linux/rknn-toolkit/tree/master/examples/onnx/yolov5
> 
> 1. 创建`conda env` with `python3.7`
>    _activate_ 此 _env_, 同时安装python dependencies by `pip3 install -r requirements.txt`.
> 2. [clone yolov5](https://github.com/ultralytics/yolov5/) 并依RKNN文档DEMO时的版本check out到此commit id上:
>    > 使用yolov5官方仓库导出模型，链接：[https://github.com/ultralytics/yolov5。该demo创建时yolov5的最新节点的commit](https://github.com/ultralytics/yolov5%E3%80%82%E8%AF%A5demo%E5%88%9B%E5%BB%BA%E6%97%B6yolov5%E7%9A%84%E6%9C%80%E6%96%B0%E8%8A%82%E7%82%B9%E7%9A%84commit) id为:c5360f6e7009eb4d05f14d1cc9dae0963e949213
>    > 并在私有数据集上训练了模型，通过detect.py一切正常。
> 3. 安装 _onnx==1.6.0_  (原因是rknn toolkit中用的是此版本的 _onnx_ ), 并执行了`export`转`.pt`转至`.onnx`.
>    ```
>    pip3 list |grep onnx
>    onnx                    1.6.0
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    虽然最后_.onnx_生成了。但同时export过程中可以**看到有个**`failure`：
>    > PyTorch: starting from runs/train/exp/weights/last.pt (14.5 MB)
>    > TorchScript: starting export with torch 1.11.0+cu102...
>    > ...
>    > ...
>    > ONNX: starting export with onnx 1.6.0...
>    > ...
>    > ONNX: export **failure**: Your model ir_version is higher than the checker's.
>    > Torch version 1.11.0+cu102 has not been tested with coremltools. You may run into unexpected errors. Torch 1.10.2 is the most recent version that has been tested.
>    > CoreML: starting export with coremltools 5.2.0...
>    > ...
>    > ...
>    
>    
>    不管它(一会再尝试用最新版本的onnx)，现仍将生成的`.onnx`拷贝至`example/onnx/yolov5/`下.
> 4. 换到rknn toolkit的`conda env`:
>    执行python3 test.py时，得到以下错误：
>    > W Call onnx.optimizer.optimize fail, skip optimize
>    > W Please confirm that your onnx opset_version <= 11 (current opset_verison = 12)!!!
>    > E Catch exception when loading onnx model: elenet_yolov5s.onnx!
>    > E Traceback (most recent call last):
>    > E   File "rknn/base/RKNNlib/RK_nn.py", line 141, in rknn.base.RKNNlib.RK_nn.RKnn.load_onnx
>    > E   File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 118, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
>    > E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 111, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.**init**
>    > E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 1059, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx._build_subgraph
>    > E   File "rknn/base/RKNNlib/converter/onnx_util.py", line 366, in rknn.base.RKNNlib.converter.onnx_util.onnx_subgraph.build_subgraph
>    > E KeyError: '378'
>    > E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
>    > E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
>    > Load yolov5 failed!
> 5. 尝试在`export yolov5`时使用最新的onnx， 即版本1.11.0， 则`export`无错：
>    > ONNX: starting export with onnx 1.11.0...
>    > /home/shao/yolov5/models/yolo.py:58: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>    > if self.grid[i].shape[2:4] != x[i].shape[2:4] or self.onnx_dynamic:
>    > ONNX: export success, saved as runs/train/exp/weights/last.onnx (28.4 MB)
>    > ONNX: run --dynamic ONNX model inference with: 'python detect.py --weights runs/train/exp/weights/last.onnx'
>    > Torch version 1.11.0+cu102 has not been tested with coremltools. You may run into unexpected errors. Torch 1.10.2 is the most recent version that has been tested.
>    > ...
>    > ...
>    
>    
>    但在rknn中执行 python3 test.py, 同样的错误。
> 
> Questions:
> 
> 1. 以上错误如何避免呢?
> 2. 在yolov4中，需要使用什么版本的`onnx`来做`export`呢？_1.6.0_ or _1.11.0_?

I am also dealing with the same error. The versions of rknn-toolkit and onnx included in yolov5 do not match. I could not export a model onnx model with outputs as in the repo.

For the Key Error '378' you mentioned, I can say:
It is related to the output name of the converted rknn model. You can see the model output name with the Netron application.

ret = rknn.load_onnx(model=ONNX_MODEL,outputs=['378', '439', '500'])
You can avoid this error if you change the line as below.
  ret = rknn.load_onnx(model=ONNX_MODEL,outputs=["output"])

But then you will get post processing error:
   -----> input1_data = outputs[1]
IndexError: list index out of range

You can use the following function to bypass this error. This function provides error avoidance. But I'm not sure if it's tranforming exactly right. Because the prediction results are not correct

def get_inputs_from_one_outputs(outputs):
    input0_data = list()
    input1_data = list()
    input2_data = list()
    for i in range(80*80*3 + 40*40*3 + 20*20*3):
        row = outputs[0][0][i]
        if i < 80*80*3:
            input0_data.append(row)
        if i >= 80*80*3 and i < 80*80*3 + 40*40*3:
            input1_data.append(row)
        if i >= 80*80*3 + 40*40*3:
            input2_data.append(row)

    input0_data = np.array(input0_data)
    input1_data = np.array(input1_data)
    input2_data = np.array(input2_data)

    print("input0_data.shape:", input0_data.shape)
    print("input1_data.shape:", input1_data.shape)
    print("input2_data.shape:", input2_data.shape)
    print()
    feature_length = outputs[0].shape[-1]
    input0_data = np.array(input0_data).reshape(1, 3*feature_length, 80, 80)
    input1_data = np.array(input1_data).reshape(1, 3*feature_length, 40, 40)
    input2_data = np.array(input2_data).reshape(1, 3*feature_length, 20, 20)


    print("input0_data.shape:", input0_data.shape)
    print("input1_data.shape:", input1_data.shape)
    print("input2_data.shape:", input2_data.shape)
    input0_data = input0_data.reshape([3,-1]+list(input0_data.shape[-2:]))
    input1_data = input1_data.reshape([3,-1]+list(input1_data.shape[-2:]))
    input2_data = input2_data.reshape([3,-1]+list(input2_data.shape[-2:]))
    print()
    print("input0_data.shape:", input0_data.shape)
    print("input1_data.shape:", input1_data.shape)
    print("input2_data.shape:", input2_data.shape)

    input0_data = np.transpose(input0_data, (2, 3, 0, 1))
    input1_data = np.transpose(input1_data, (2, 3, 0, 1))
    input2_data = np.transpose(input2_data, (2, 3, 0, 1))

    print()
    print("input0_data.shape:", input0_data.shape)
    print("input1_data.shape:", input1_data.shape)
    print("input2_data.shape:", input2_data.shape)
    
    return (input0_data, input1_data, input2_data)

As a result, I have not been able to convert a rknn working model as of now.

**Comment by serkanpeldek** [comment]
https://github.com/rockchip-linux/rknn-toolkit/issues/225

**Comment by shaojun** [comment]
this has been clarified at https://github.com/rockchip-linux/rknn-toolkit/issues/225#issuecomment-1103447609
