### ISSUE TITLE
yolov5 推理时延

### ISSUE THREAD

**Issue by MaitreChen** [rockchip-linux/rknn-toolkit#237]
在虚拟机ubuntu18.04上跑yolo v5 demo，模型是onnx格式的，单张图片推理时延为80s，正常吗？如果用开发板跑是不是会有大幅提升？

**Comment by zen-xingle** [comment]
80s? 可能是用了模拟器推理？

yolov5 可以参考这里 https://github.com/airockchip/rknn_model_zoo/tree/main/models/vision/object_detection/yolov5-pytorch

**Comment by MaitreChen** [comment]
的确如此，这是正常现象，谢谢~~
