### ISSUE TITLE
pytorch 转成caffe格式，再赚rknn模型报错

### ISSUE THREAD

**Issue by Oliverwang** [rockchip-linux/rknn-toolkit#29]
加载caffe模型的时候报 W Warning: Axis may need to be adjusted according to original model shape. 这个警告             hybrid_quantization_step1 的时候  ValueError: cannot reshape array of size 2359296 into shape (1,576,1024,3)

**Comment by gxd1994** [comment]
请问下, 这个问题怎么解决的? 好像是reshape op 不支持4D tensor 输入造成的
