### ISSUE TITLE
rknn_toolkit_lite-1.7.3-cp38-cp38-linux_x86_64.whl 无法安装onnx=1.6.0

### ISSUE THREAD

**Issue by kingzcheung** [rockchip-linux/rknn-toolkit#320]
python 3.8 并不支持 onnx=1.6.0 吧？

https://github.com/onnx/onnx/issues/2734

我对 METADATA 做了以下修改才安装通过

```
Requires-Dist: onnx (>=1.6.0)
```

**Comment by sankexin** [comment]
onnx=1.12.0 can use

**Comment by sankexin** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
