### ISSUE TITLE
reshape error

### ISSUE THREAD

**Issue by winterxx** [rockchip-linux/rknn-toolkit#375]
toolkit1.7.3

![2023-06-06 16-59-23屏幕截图_](https://github.com/rockchip-linux/rknn-toolkit/assets/32504396/2899e50d-e426-4ce6-a340-475867fde997)

E ValueError: Cannot reshape a tensor with 360 elements to shape [0,40,120] (0 elements) for '{{node Reshape_Reshape_8_82/Reshape_Reshape_8_82}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32](Transpose_Transpose_3_93/Transpose_Transpose_3_93, Reshape_Reshape_8_82/Reshape_Reshape_8_82/shape)' with input shapes: [1,15,3,8], [3] and with input tensors computed as partial shapes: input[1] = [0,40,120].

**Comment by broljx** [comment]
您好，后面解决了没？我也遇到类似的问题

**Comment by winterxx** [comment]
> 您好，后面解决了没？我也遇到类似的问题

使用最新的工具即可
