### ISSUE TITLE
关于算子支持问题

### ISSUE THREAD

**Issue by AntyRia** [rockchip-linux/rknn-toolkit#417]
你好 想问问关于音频处理类的模型中，包含的对数算子不支持，请问有什么好的替代方案吗，或者你们后续会更新支持吗

**Comment by eRaul** [comment]
pytorch的torch.log是支持的。

**Comment by ttaohe** [comment]
![image](https://github.com/rockchip-linux/rknn-toolkit/assets/110707902/fb1cbf76-66ea-4db8-92e6-1ae0c6ef622e)
对数算子不支持，请问有什么好的解决方法吗？

**Comment by eRaul** [comment]
> ![image](https://private-user-images.githubusercontent.com/110707902/289364410-fb1cbf76-66ea-4db8-92e6-1ae0c6ef622e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjQwNjUsIm5iZiI6MTcwMjI2Mzc2NSwicGF0aCI6Ii8xMTA3MDc5MDIvMjg5MzY0NDEwLWZiMWNiZjc2LTY2ZWEtNGRiOC05MmU2LTFhZTBjNmVmNjIyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQwMzAyNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjFlMjQxZDUyNzkzYWZkYWVjODJmZDQzZDQ0OWNiNmJjNjBkZDU2YTczMmZkZTQxMzI0YWUyYzFiYzYwNWUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5JP6g1_YOoGMXbAbBpH-wczzGXpH2IZKP9WoRFN79Kg) 对数算子不支持，请问有什么好的解决方法吗？

这个是什么框架的模型转rknn报错。贴个完整点的日志

**Comment by ttaohe** [comment]
> > ![image](https://private-user-images.githubusercontent.com/110707902/289364410-fb1cbf76-66ea-4db8-92e6-1ae0c6ef622e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjQwNjUsIm5iZiI6MTcwMjI2Mzc2NSwicGF0aCI6Ii8xMTA3MDc5MDIvMjg5MzY0NDEwLWZiMWNiZjc2LTY2ZWEtNGRiOC05MmU2LTFhZTBjNmVmNjIyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQwMzAyNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjFlMjQxZDUyNzkzYWZkYWVjODJmZDQzZDQ0OWNiNmJjNjBkZDU2YTczMmZkZTQxMzI0YWUyYzFiYzYwNWUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5JP6g1_YOoGMXbAbBpH-wczzGXpH2IZKP9WoRFN79Kg) 对数算子不支持，请问有什么好的解决方法吗？
> 
> 这个是什么框架的模型转rknn报错。贴个完整点的日志

我把pytorch模型转为onnx后，再将onnx转为rknn会报log算子不支持，是目前log计算还不支持吗？我看官方的支持算子文档里确实没有log

**Comment by AntyRia** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/110707902/289364410-fb1cbf76-66ea-4db8-92e6-1ae0c6ef622e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjQwNjUsIm5iZiI6MTcwMjI2Mzc2NSwicGF0aCI6Ii8xMTA3MDc5MDIvMjg5MzY0NDEwLWZiMWNiZjc2LTY2ZWEtNGRiOC05MmU2LTFhZTBjNmVmNjIyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQwMzAyNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjFlMjQxZDUyNzkzYWZkYWVjODJmZDQzZDQ0OWNiNmJjNjBkZDU2YTczMmZkZTQxMzI0YWUyYzFiYzYwNWUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5JP6g1_YOoGMXbAbBpH-wczzGXpH2IZKP9WoRFN79Kg) 对数算子不支持，请问有什么好的解决方法吗？
> > 
> > 
> > 这个是什么框架的模型转rknn报错。贴个完整点的日志
> 
> 我把pytorch模型转为onnx后，再将onnx转为rknn会报log算子不支持，是目前log计算还不支持吗？我看官方的支持算子文档里确实没有log

是的 确实是不支持的 我后来把模型拆开了 不支持的操作cpu做
