### ISSUE TITLE
运动量化精度分析报错，这就是log里的全部信息

### ISSUE THREAD

**Issue by 7yzx** [rockchip-linux/rknn-toolkit#418]
使用的是1.7.3版本，是自己跑的lighttrack的onnx转成的rknn模型，在精度分析这里卡住了。不知道是什么错误
```D Using CPPUTILS: True
E Catch exception when snapshot: AttributeError("'Namespace' object has no attribute 'can_snapshot'",)
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 850, in rknn.api.rknn_base.RKNNBase.accuracy_analysis
E AttributeError: 'Namespace' object has no attribute 'can_snapshot'
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues```

**Comment by eRaul** [comment]
请先尝试最新的1.7.5版本，如果问题还未解决，请附上复现问题的模型。

**Comment by 7yzx** [comment]
好的，安装最新已解决，感谢回复

**Comment by RamatovInomjon** [comment]
W rknn-toolkit version: 1.7.5
W The target and target_platform in config are different!
W The rv1126 will be used as the target device during accuracy analysis.
E Catch exception when snapshot: AttributeError("'Namespace' object has no attribute 'can_snapshot'")
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 914, in rknn.api.rknn_base.RKNNBase.accuracy_analysis
E AttributeError: 'Namespace' object has no attribute 'can_snapshot'
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
[custom_agw_R50.zip](https://github.com/rockchip-linux/rknn-toolkit/files/14204534/custom_agw_R50.zip)

**Comment by RamatovInomjon** [comment]
@eRaul Hi Can you check the issue please?

**Comment by eRaul** [comment]
> @eRaul Hi Can you check the issue please?

Can you provide log file <log_feedback_to_the_rknn_toolkit_dev_team.log>?
