### ISSUE TITLE
Cannot reshape a tensor with 25600000 elements to shape [100,80,20,20]  求大佬看看这个怎么解决呀

### ISSUE THREAD

**Issue by booty-chw** [rockchip-linux/rknn-toolkit#425]
[log_feedback_to_the_rknn_toolkit_dev_team.log](https://github.com/rockchip-linux/rknn-toolkit/files/13761032/log_feedback_to_the_rknn_toolkit_dev_team.log)
ValueError: Cannot reshape a tensor with 25600000 elements to shape [100,80,20,20] (3200000 elements) for '{{node Reshape_/model.10/Reshape_294/Reshape_/model.10/Reshape_294}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32](Reshape_/model.10/Reshape_294_RKNN_mark_perm_918/Reshape_/model.10/Reshape_294_RKNN_mark_perm_918, Reshape_/model.10/Reshape_294/Reshape_/model.10/Reshape_294/shape)' with input shapes: [100,640,20,20], [4] and with input tensors computed as partial shapes: input[1] = [100,80,20,20].

**Comment by 17656178609** [comment]
[log_feedback_to_the_rknn_toolkit_dev_team.log](https://github.com/rockchip-linux/rknn-toolkit/files/13761028/log_feedback_to_the_rknn_toolkit_dev_team.log)

**Comment by eRaul** [comment]
在config接口中把batch_size设成1试试。

**Comment by KopiSoftware** [comment]
> 在config接口中把batch_size设成1试试。

Thank you VERY much. It works in my case when I try to convert rtmpose into rknn model.
