### ISSUE TITLE
rv1126 后量化后输出节点精度显著降低

### ISSUE THREAD

**Issue by RookieHuang** [rockchip-linux/rknn-toolkit#427]
使用[model.zip](https://github.com/rockchip-linux/rknn-toolkit/files/13848230/model.zip)模型进行rknn工具进行后量化后，在rv1126上推理的输出节点与原始模型存在很大差异。
采用量化分析工具分析发现仅最后有两个节点的eculidean_norm较大，cosine_norm较小，请问如何解决？
![image](https://github.com/rockchip-linux/rknn-toolkit/assets/48719225/4f972ad4-4ee0-455c-897b-6e62feb081cc)

**Comment by eRaul** [comment]
可以试下混合量化。直接用默认的混合量化配置。

**Comment by RookieHuang** [comment]
> 可以试下混合量化。直接用默认的混合量化配置。

@eRaul 仅对最后两个节点用fp16精度，推理速度直接慢了快一倍，请问下这种情况正常吗？

**Comment by RookieHuang** [comment]
@eRaul 另外请问一下用python api rknn.inference推理出来的结果和c api中从output.buf（output.wan_float=1）中取出来的结果不太一致是正常的吗？

**Comment by eRaul** [comment]
> > 可以试下混合量化。直接用默认的混合量化配置。
> 
> @eRaul 仅对最后两个节点用fp16精度，推理速度直接慢了快一倍，请问下这种情况正常吗？

贴下混合量化前后的性能分析结果。

**Comment by eRaul** [comment]
> @eRaul 另外请问一下用python api rknn.inference推理出来的结果和c api中从output.buf（output.wan_float=1）中取出来的结果不太一致是正常的吗？

算下余弦距离，看下差多少？

**Comment by SoulProficiency** [comment]
I Insert converter layer Conv_Conv_145_8_pre_asymmetric_affineu8_to_dynamic_fixed_pointi16_153 before Conv_Conv_145_8.
I Insert converter layer Conv_Conv_145_8_next_dynamic_fixed_pointi16_to_asymmetric_affineu8_154 after Conv_Conv_145_8.
I Insert converter layer Conv_Conv_147_7_pre_asymmetric_affineu8_to_dynamic_fixed_pointi16_155 before Conv_Conv_147_7.
I Insert converter layer Conv_Conv_147_7_next_dynamic_fixed_pointi16_to_asymmetric_affineu8_156 after Conv_Conv_147_7.
E Catch exception when direct build RKNN model!
E Traceback (most recent call last):
E   File "rknn/base/RKNNlib/app/medusa/quantization.py", line 51, in rknn.base.RKNNlib.app.medusa.quantization.Quantization._run_quantization
E   File "rknn/base/RKNNlib/app/medusa/quantization.py", line 92, in rknn.base.RKNNlib.app.medusa.quantization.Quantization._quantize_net
E   File "rknn/base/RKNNlib/app/medusa/quantization.py", line 130, in rknn.base.RKNNlib.app.medusa.quantization.Quantization._generate_hybrid_table
E   File "rknn/base/RKNNlib/optimize/optimizer.py", line 437, in rknn.base.RKNNlib.optimize.optimizer.Optimizer.apply
E   File "rknn/base/RKNNlib/optimize/rules/quantize/hybrid_insert_converter_layer.py", line 223, in rknn.base.RKNNlib.optimize.rules.quantize.hybrid_insert_converter_layer.HybridInsertConverterLayer.apply
E AttributeError: 'NoneType' object has no attribute 'is_op'
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
E RKNN model data is None, please load model first!
E RKNN model data is None, please load model first!
请问这个是什么问题啊？
