### ISSUE TITLE
[rknn result error] rknn result cannot aligned to onnx result

### ISSUE THREAD

**Issue by IcewineChen** [rockchip-linux/rknn-toolkit#451]
I convert the rknn model from onnx model successfully, but during testing, the results from rknn cannot aligned to onnx. All the ops of my model follows https://github.com/rockchip-linux/rknn-toolkit2/blob/master/doc/RKNN-Toolkit2_OP_Support-1.6.0.md.
![issue](https://github.com/rockchip-linux/rknn-toolkit/assets/23411315/1feb0c9d-74e1-4102-a409-d6307540b89b)
How could I aligned different format models results?

**Comment by gaoxumustwin** [comment]
Hello friend, may I ask how you solved this problem
