### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './optimize.onnx'

### ISSUE THREAD

**Issue by BITfanyu** [rockchip-linux/rknn-toolkit#484]
RV1126/model_convert/rknn_convert$ python3 rknn_convert.py yolov11s_uav_h640_w384.onnx rv1126
W rknn-toolkit version: 1.7.5
--> Config model
done
--> Loading model
Unsupport onnx opset 17, need <= 12!
E Catch exception when loading onnx model: ./optimize.onnx!
E Traceback (most recent call last):
E   File "rknn/api/rknn_base.py", line 376, in rknn.api.rknn_base.RKNNBase.load_onnx
E   File "rknn/base/RKNNlib/RK_nn.py", line 151, in rknn.base.RKNNlib.RK_nn.RKnn.load_onnx
E   File "rknn/base/RKNNlib/app/importer/import_onnx.py", line 120, in rknn.base.RKNNlib.app.importer.import_onnx.Importonnx.run
E   File "rknn/base/RKNNlib/converter/convert_onnx.py", line 71, in rknn.base.RKNNlib.converter.convert_onnx.convert_onnx.__init__
E FileNotFoundError: [Errno 2] No such file or directory: './optimize.onnx'
E Please feedback the detailed log file <log_feedback_to_the_rknn_toolkit_dev_team.log> to the RKNN Toolkit development team.
E You can also check github issues: https://github.com/rockchip-linux/rknn-toolkit/issues
Load model failed!

**Comment by Frank24B951037** [comment]
你好，我也碰到了这个问题，能否请问一下如何解决这个问题？

**Comment by Sherlock-hh** [comment]
> 你好，我也碰到了这个问题，能否请问一下如何解决这个问题？

你好，请问你解决了这个问题吗？

**Comment by fanronghua0123456** [comment]
在 模型转换的时候，设置 opset=12，即可！！

from ultralytics import YOLO


if __name__ == '__main__':

    # 加载你的 YOLOv11 模型
    model = YOLO('runs/detect/train/best.pt')  # 替换为你的模型路径

    # 导出为 ONNX
    #model.export(format='tflite',int8=True)
    #model.export(format='tflite',opset=12,int8=True)

    model.export(format="onnx", opset=12)

    # Export the model to RKNN format
    # 'name' can be one of rk3588, rk3576, rk3566, rk3568, rk3562, rv1103, rv1106, rv1103b, rv1106b, rk2118
    #model.export(format="rknn", name="rv1106")  # creates '/yolo11n_rknn_model'
