### ISSUE TITLE
模型如何配置可以在CPU上推理?

### ISSUE THREAD

**Issue by fangwudi** [rockchip-linux/rknn-toolkit#80]
你好,请教下,是否可以在什么地方配置使得模型不使用NPU而是CPU进行推理？如果可以的话，底层的执行框架是什么？

**Comment by eRaul** [comment]
> 你好,请教下,是否可以在什么地方配置使得模型不使用NPU而是CPU进行推理？如果可以的话，底层的执行框架是什么？

目前没有这样的配置。
