### ISSUE TITLE
Yolov5 模型,打开量化并指定输出结点为神经网络的最终结点,则得到的数据大部分为0.0

### ISSUE THREAD

**Issue by liangbch** [rockchip-linux/rknn-toolkit#93]
重现步骤:
 基于 examples/onnx/yolov5/test.py 

在244行,将
  ret = rknn.load_onnx(model=ONNX_MODEL,outputs=['396', '458', '520'])
改为
  ret = rknn.load_onnx(model=ONNX_MODEL,outputs=['output'])

在306行, 将
    input0_data = outputs[0]
    input1_data = outputs[1]
    input2_data = outputs[2]
改为
    input0_data = outputs[0]

结果:
  检查 input0_data, 会发现,大部分数据都是0

但是,如果关闭量化, 即在252行, 将
   ret = rknn.build(do_quantization=QUANTIZE_ON, dataset=DATASET)
改为
   ret = rknn.build(do_quantization=False, dataset=DATASET)

并仍指定输出结点为 'output', 则numpy array input0_data的大部分数量都是有效的.

**Comment by zen-xingle** [comment]
在进行量化的情况下，在output节点包含坐标信息和置信度信息，坐标的数值范围为[0,img_size]（通常为640/416），而置信度的数值范围为[0,1]。量化过程中置信度的值会由于尺度太小，与坐标 concat 到同一个 tensor 时造成置信度值的精度丢失，所以会出现你说的output节点大部分数据都是0的情况。

这个问题是量化的特性，而非bug。

推荐使用example的输出形式去做量化。或者你可以考虑修改模型，避免将 position 和 score 合并到同一个tensor里面。

**Comment by liangbch** [comment]
明白了,和我预想的一样.量化时,使用8bit整数类型来表示一个数据,为了保证在同一批数据中,最大的值不致溢出,最小的数就变成0了.

**Comment by yinzeq** [comment]
遇到了一个同样的问题，模型是centernet，i16量化精度没有损失，u8量化惨不忍睹。怀疑是这个问题，但是我的输出也是分开写的。配置方式大概是：
    ret = rknnobj.load_onnx(model=model_path,
                         outputs=['kp_scores','kp_regs','kp_offset']
                         )
模型输出节点截图：
<img width="589" alt="企业微信截图_16406801603823" src="https://user-images.githubusercontent.com/95479167/147545849-bc9c6ae5-77f1-4221-bba3-20d0ff755107.png">
不知道是不是这个问题

**Comment by zen-xingle** [comment]
> 

可以试下精度分析，把掉精度多的层做个混合i16量化，具体请看userguide相关内容

**Comment by PerLightFlow** [comment]
> 在进行量化的情况下，在output节点包含坐标信息和置信度信息，坐标的数值范围为[0,img_size]（通常为640/416），而置信度的数值范围为[0,1]。量化过程中置信度的值会由于尺度太小，与坐标 concat 到同一个 tensor 时造成置信度值的精度丢失，所以会出现你说的output节点大部分数据都是0的情况。
> 
> 这个问题是量化的特性，而非bug。
> 
> 推荐使用example的输出形式去做量化。或者你可以考虑修改模型，避免将 position 和 score 合并到同一个tensor里面。

但是我量化后在模拟器中连接板子使用板子上的npu进行推理验证时候（即设置ret = rknn.init_runtime(target='rv1126')）这时候推理结果没有问题，但是后面使用C++部署在板子上推理时候发现就出现了置信度的数值由于尺度太小而被置零现象。这是为什么？对于同一个量化模型使用模拟器调用板子npu推理验证的和板子上部署推理出现了不同的结果（这里指置信度被置零问题）
