### ISSUE TITLE
点云模型转换大小异常，加载返回错误码-6

### ISSUE THREAD

**Issue by 0x6c0x62** [rockchip-linux/rknn-toolkit#97]
你好，我现在有两个处理点云数据的模型。
两个模型的原始大小均为20M左右，输入数据格式是float16。均采用不量化，非预编译进行转换

其中一个模型1个输入，3个输出。转换出来10M左右，放到板子上也可以正常运行。
另外一个模型7个输入，1个输出。转换出来只有280K，采用预编译，转换出来居然只有4K，在服务器上通过python接口load_rknn居然都能加载成功，返回0。但是放到板子上加载时报错，返回-6。这个模型转换时并没有报错，但是我觉得大小差距有点太夸张了。

请问我应该从哪方面寻找问题呢？

**Comment by eRaul** [comment]
这个模型在转换过程中可能只转了部分节点，你可以通过以下方式查看转换后的RKNN模型节点：
1. 使用netron查看RKNN模型
2. 使用RKNN Toolkit的可视化工具加载转换后的RKNN模型
注：因为转成预编译模型后所有节点信息的详情都会被隐藏，所以需要在转换过程中将预编译关掉。
你也可以在创建RKNN对象时设置verbose=True，观察转换过程中的详细日志。

**Comment by 0x6c0x62** [comment]
> 这个模型在转换过程中可能只转了部分节点，你可以通过以下方式查看转换后的RKNN模型节点：
> 
> 1. 使用netron查看RKNN模型
> 2. 使用RKNN Toolkit的可视化工具加载转换后的RKNN模型
>    注：因为转成预编译模型后所有节点信息的详情都会被隐藏，所以需要在转换过程中将预编译关掉。
>    你也可以在创建RKNN对象时设置verbose=True，观察转换过程中的详细日志。

**Comment by 0x6c0x62** [comment]
![1](https://user-images.githubusercontent.com/24402863/133361188-ebd8c8b2-6996-4142-9224-14c2ad349ebb.png)
![2](https://user-images.githubusercontent.com/24402863/133361194-f3ff9291-bf74-439d-a42c-770c6089040f.png)
![3](https://user-images.githubusercontent.com/24402863/133361201-1d2e488c-2bef-404d-88b3-07f634e479ac.png)

我看了一下，这两个层好像被合并了，日志里面打印也显示这两个层被合并了。导致最后的输出大小不对了，有办法关闭这个合并吗？

**Comment by 0x6c0x62** [comment]
root@d9fcccf5d2a2:/app/rknn_transfer/test/dianyun# python3 convert.py 
W Verbose file path is invalid, debug info will not dump to file.
D Using CPPUTILS: True
--> config model
W All optimization will be closed. This may cause model conversions to fail or fail to run!!!
done
--> Loading model
I Start importing onnx...
I Current ONNX Model use ir_version 4 opset_version 9
I Call RKNN onnx optimize fail, skip optimize
D Calc tensor Sub_166 (1, 1, 6815, 100)
D Calc tensor Concat_159 (1, 3, 6815, 100)
D Calc tensor ReduceSum_160 (1, 3, 6815, 1)
D Calc tensor Sub_165 (1, 1, 6815, 100)
D Calc tensor Concat_167 (1, 2, 6815, 100)
D Calc tensor Concat_168 (1, 4, 6815, 100)
D Calc tensor Initializer_161 (4,)
D Calc tensor Reshape_162 (1, 1, 6815, 1)
D Calc tensor Div_163 (1, 3, 6815, 1)
D Calc tensor Sub_164 (1, 3, 6815, 100)
D Calc tensor Concat_169 (1, 9, 6815, 100)
D Calc tensor Mul_170 (1, 9, 6815, 100)
D Calc tensor Initializer_voxel_feature_extractor.pfn_layers.0.norm.weight (64,)
D Calc tensor Initializer_voxel_feature_extractor.pfn_layers.0.norm.running_var (64,)
D Calc tensor Initializer_voxel_feature_extractor.pfn_layers.0.norm.running_mean (64,)
D Calc tensor Initializer_voxel_feature_extractor.pfn_layers.0.norm.bias (64,)
D Calc tensor Initializer_voxel_feature_extractor.pfn_layers.0.conv3.weight (64, 64, 1, 34)
D Calc tensor Initializer_voxel_feature_extractor.pfn_layers.0.conv3.bias (64,)
D Calc tensor Initializer_voxel_feature_extractor.pfn_layers.0.conv1.weight (64, 9, 1, 1)
D Calc tensor Initializer_voxel_feature_extractor.pfn_layers.0.conv1.bias (64,)
D Calc tensor Conv_171 (1, 64, 6815, 100)
D Calc tensor BatchNormalization_172 (1, 64, 6815, 100)
D Calc tensor Relu_173 (1, 64, 6815, 100)
D Calc tensor Conv_174 (1, 64, 6815, 1)
D import clients finished
I build output layer attach_Conv_174:out0
I Try match Conv_174:out0
I Match r_conv [['Conv_174', 'Initializer_voxel_feature_extractor.pfn_layers.0.conv3.weight', 'Initializer_voxel_feature_extractor.pfn_layers.0.conv3.bias']] [['Conv', 'Constant_0', 'Constant_1']] to [['convolution']]
I Try match Relu_173:out0
I Match r_relu [['Relu_173']] [['Relu']] to [['relu']]
I Try match BatchNormalization_172:out0
I Match r_bn_v6 [['BatchNormalization_172', 'Initializer_voxel_feature_extractor.pfn_layers.0.norm.weight', 'Initializer_voxel_feature_extractor.pfn_layers.0.norm.bias', 'Initializer_voxel_feature_extractor.pfn_layers.0.norm.running_mean', 'Initializer_voxel_feature_extractor.pfn_layers.0.norm.running_var']] [['BatchNormalization', 'Constant_0', 'Constant_1', 'Constant_2', 'Constant_3']] to [['batchnormalize']]
I Try match Conv_171:out0
I Match r_conv [['Conv_171', 'Initializer_voxel_feature_extractor.pfn_layers.0.conv1.weight', 'Initializer_voxel_feature_extractor.pfn_layers.0.conv1.bias']] [['Conv', 'Constant_0', 'Constant_1']] to [['convolution']]
I Try match Mul_170:out0
I Match r_mul [['Mul_170']] [['Mul']] to [['multiply']]
I Try match Concat_169:out0
I Match concat_3 [['Concat_169']] [['Concat']] to [['concat']]
I Try match Concat_167:out0
I Match concat_2 [['Concat_167']] [['Concat']] to [['concat']]
I Try match Concat_168:out0
I Match concat_4 [['Concat_168']] [['Concat']] to [['concat']]
I Try match Sub_164:out0
I Match r_sub [['Sub_164']] [['Sub']] to [['subtract']]
I Try match Sub_165:out0
I Match r_sub [['Sub_165']] [['Sub']] to [['subtract']]
I Try match Sub_166:out0
I Match r_sub [['Sub_166']] [['Sub']] to [['subtract']]
I Try match Div_163:out0
I Match r_div [['Div_163']] [['Div']] to [['divide']]
I Try match Reshape_162:out0
I Match r_rsp_v5 [['Reshape_162', 'Initializer_161']] [['Reshape', 'Constant_0']] to [['reshape']]
I Try match ReduceSum_160:out0
I Match r_reducesum [['ReduceSum_160']] [['ReduceSum']] to [['reducesum']]
I Try match Concat_159:out0
I Match concat_3 [['Concat_159']] [['Concat']] to [['concat']]
W Input channel 1 less then 3, please update NPU Driver to v1.3.0 or later.
I build input layer pillar_x:out0
W Input channel 1 less then 3, please update NPU Driver to v1.3.0 or later.
I build input layer pillar_y:out0
W Input channel 1 less then 3, please update NPU Driver to v1.3.0 or later.
I build input layer pillar_z:out0
W Input channel 1 less then 3, please update NPU Driver to v1.3.0 or later.
I build input layer pillar_i:out0
W Channels(6815) of input node: num_points_per_pillar:out0 > 128, mean/std values will be set to default 0/1.
W Please do pre-processing manually before inference.
I build input layer num_points_per_pillar:out0
W Input channel 1 less then 3, please update NPU Driver to v1.3.0 or later.
I build input layer x_sub_shaped:out0
W Input channel 1 less then 3, please update NPU Driver to v1.3.0 or later.
I build input layer y_sub_shaped:out0
W Input channel 1 less then 3, please update NPU Driver to v1.3.0 or later.
I build input layer mask:out0
D connect Relu_173_2 0  ~ Conv_174_1 0
D connect BatchNormalization_172_3 0  ~ Relu_173_2 0
D connect Conv_171_4 0  ~ BatchNormalization_172_3 0
D connect Mul_170_5 0  ~ Conv_171_4 0
D connect Concat_169_6 0  ~ Mul_170_5 0
D connect mask_23 0  ~ Mul_170_5 1
D connect Concat_168_8 0  ~ Concat_169_6 0
D connect Sub_164_9 0  ~ Concat_169_6 1
D connect Concat_167_7 0  ~ Concat_169_6 2
D connect Sub_165_10 0  ~ Concat_167_7 0
D connect Sub_166_11 0  ~ Concat_167_7 1
D connect pillar_x_16 0  ~ Concat_168_8 0
D connect pillar_y_17 0  ~ Concat_168_8 1
D connect pillar_z_18 0  ~ Concat_168_8 2
D connect pillar_i_19 0  ~ Concat_168_8 3
D connect Concat_159_15 0  ~ Sub_164_9 0
D connect Div_163_12 0  ~ Sub_164_9 1
D connect pillar_x_16 0  ~ Sub_165_10 0
D connect x_sub_shaped_21 0  ~ Sub_165_10 1
D connect pillar_y_17 0  ~ Sub_166_11 0
D connect y_sub_shaped_22 0  ~ Sub_166_11 1
D connect ReduceSum_160_14 0  ~ Div_163_12 0
D connect Reshape_162_13 0  ~ Div_163_12 1
D connect num_points_per_pillar_20 0  ~ Reshape_162_13 0
D connect Concat_159_15 0  ~ ReduceSum_160_14 0
D connect pillar_x_16 0  ~ Concat_159_15 0
D connect pillar_y_17 0  ~ Concat_159_15 1
D connect pillar_z_18 0  ~ Concat_159_15 2
D connect Conv_174_1 0  ~ attach_Conv_174/out0_0 0
W:tensorflow:From /usr/local/lib/python3.6/dist-packages/rknn/api/rknn.py:129: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

W:tensorflow:From /usr/local/lib/python3.6/dist-packages/rknn/api/rknn.py:129: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2021-09-15 02:44:12.236408: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-09-15 02:44:12.255952: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2099880000 Hz
2021-09-15 02:44:12.257808: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x8e83e00 executing computations on platform Host. Devices:
2021-09-15 02:44:12.257848: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
W:tensorflow:From /usr/local/lib/python3.6/dist-packages/rknn/api/rknn.py:129: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

D Process pillar_x_16 ...
D RKNN output shape(input): (1 6815 100 1)
D Tensor @pillar_x_16:out0 type: float32
D Process pillar_y_17 ...
D RKNN output shape(input): (1 6815 100 1)
D Tensor @pillar_y_17:out0 type: float32
D Process pillar_z_18 ...
D RKNN output shape(input): (1 6815 100 1)
D Tensor @pillar_z_18:out0 type: float32
D Process pillar_i_19 ...
D RKNN output shape(input): (1 6815 100 1)
D Tensor @pillar_i_19:out0 type: float32
D Process Concat_168_8 ...
D RKNN output shape(concat): (1 6815 100 4)
D Tensor @Concat_168_8:out0 type: float32
D Process Concat_159_15 ...
D RKNN output shape(concat): (1 6815 100 3)
D Tensor @Concat_159_15:out0 type: float32
D Process ReduceSum_160_14 ...
D RKNN output shape(reducesum): (1 6815 1 3)
D Tensor @ReduceSum_160_14:out0 type: float32
D Process num_points_per_pillar_20 ...
D RKNN output shape(input): (1 6815)
D Tensor @num_points_per_pillar_20:out0 type: float32
D Process Reshape_162_13 ...
D RKNN output shape(reshape): (1 6815 1 1)
D Tensor @Reshape_162_13:out0 type: float32
D Process Div_163_12 ...
D RKNN output shape(Divide): (1 6815 1 3)
D Tensor @Div_163_12:out0 type: float32
D Process Sub_164_9 ...
D RKNN output shape(Subtract): (1 6815 100 3)
D Tensor @Sub_164_9:out0 type: float32
D Process x_sub_shaped_21 ...
D RKNN output shape(input): (1 6815 100 1)
D Tensor @x_sub_shaped_21:out0 type: float32
D Process Sub_165_10 ...
D RKNN output shape(Subtract): (1 6815 100 1)
D Tensor @Sub_165_10:out0 type: float32
D Process y_sub_shaped_22 ...
D RKNN output shape(input): (1 6815 100 1)
D Tensor @y_sub_shaped_22:out0 type: float32
D Process Sub_166_11 ...
D RKNN output shape(Subtract): (1 6815 100 1)
D Tensor @Sub_166_11:out0 type: float32
D Process Concat_167_7 ...
D RKNN output shape(concat): (1 6815 100 2)
D Tensor @Concat_167_7:out0 type: float32
D Process Concat_169_6 ...
D RKNN output shape(concat): (1 6815 100 9)
D Tensor @Concat_169_6:out0 type: float32
D Process mask_23 ...
D RKNN output shape(input): (1 6815 100 1)
D Tensor @mask_23:out0 type: float32
D Process Mul_170_5 ...
D RKNN output shape(multiply): (1 6815 100 9)
D Tensor @Mul_170_5:out0 type: float32
D Process Conv_171_4 ...
D RKNN output shape(convolution): (1 6815 100 64)
D Tensor @Conv_171_4:out0 type: float32
D Process BatchNormalization_172_3 ...
D RKNN output shape(batchnormalize): (1 6815 100 64)
D Tensor @BatchNormalization_172_3:out0 type: float32
D Process Relu_173_2 ...
D RKNN output shape(relu): (1 6815 100 64)
D Tensor @Relu_173_2:out0 type: float32
D Process Conv_174_1 ...
D RKNN output shape(convolution): (1 6815 67 64)
D Tensor @Conv_174_1:out0 type: float32
D Process attach_Conv_174/out0_0 ...
D RKNN output shape(output): (1 6815 67 64)
D Tensor @attach_Conv_174/out0_0:out0 type: float32
I Build torch-jit-export complete.
I Start C2T Switcher...
D Optimizing network with broadcast_op
D convert ReduceSum_160_14(reducesum) axes [3] to [2]
D convert Concat_168_8(concat) axis 1 to 3
D convert Concat_159_15(concat) axis 1 to 3
D convert Concat_167_7(concat) axis 1 to 3
D convert Mul_170_5(multiply) axis 1 to 3
D convert Concat_169_6(concat) axis 1 to 3
D insert permute Div_163_12_RKNN_mark_perm_24 before Div_163_12
I End C2T Switcher...
I End importing onnx...
done
--> Building model
I Generate input meta ...
I Load input meta
I Generate input meta ...
D import clients finished
I Load net...
I Load data...
I Load input meta
D Process pillar_x_16 ...
D RKNN output shape(input): (1 6815 100 1)
D Tensor @pillar_x_16:out0 type: float32
D Process pillar_y_17 ...
D RKNN output shape(input): (1 6815 100 1)
D Tensor @pillar_y_17:out0 type: float32
D Process pillar_z_18 ...
D RKNN output shape(input): (1 6815 100 1)
D Tensor @pillar_z_18:out0 type: float32
D Process pillar_i_19 ...
D RKNN output shape(input): (1 6815 100 1)
D Tensor @pillar_i_19:out0 type: float32
D Process Concat_168_8 ...
D RKNN output shape(concat): (1 6815 100 4)
D Tensor @Concat_168_8:out0 type: float32
D Process Concat_159_15 ...
D RKNN output shape(concat): (1 6815 100 3)
D Tensor @Concat_159_15:out0 type: float32
D Process ReduceSum_160_14 ...
D RKNN output shape(reducesum): (1 6815 1 3)
D Tensor @ReduceSum_160_14:out0 type: float32
D Process num_points_per_pillar_20 ...
D RKNN output shape(input): (1 6815)
D Tensor @num_points_per_pillar_20:out0 type: float32
D Process Reshape_162_13 ...
D RKNN output shape(reshape): (1 1 6815 1)
D Tensor @Reshape_162_13:out0 type: float32
D Process Div_163_12_RKNN_mark_perm_24 ...
D RKNN output shape(permute): (1 6815 1 1)
D Tensor @Div_163_12_RKNN_mark_perm_24:out0 type: float32
D Process Div_163_12 ...
D RKNN output shape(Divide): (1 6815 1 3)
D Tensor @Div_163_12:out0 type: float32
D Process Sub_164_9 ...
D RKNN output shape(Subtract): (1 6815 100 3)
D Tensor @Sub_164_9:out0 type: float32
D Process x_sub_shaped_21 ...
D RKNN output shape(input): (1 6815 100 1)
D Tensor @x_sub_shaped_21:out0 type: float32
D Process Sub_165_10 ...
D RKNN output shape(Subtract): (1 6815 100 1)
D Tensor @Sub_165_10:out0 type: float32
D Process y_sub_shaped_22 ...
D RKNN output shape(input): (1 6815 100 1)
D Tensor @y_sub_shaped_22:out0 type: float32
D Process Sub_166_11 ...
D RKNN output shape(Subtract): (1 6815 100 1)
D Tensor @Sub_166_11:out0 type: float32
D Process Concat_167_7 ...
D RKNN output shape(concat): (1 6815 100 2)
D Tensor @Concat_167_7:out0 type: float32
D Process Concat_169_6 ...
D RKNN output shape(concat): (1 6815 100 9)
D Tensor @Concat_169_6:out0 type: float32
D Process mask_23 ...
D RKNN output shape(input): (1 6815 100 1)
D Tensor @mask_23:out0 type: float32
D Process Mul_170_5 ...
D RKNN output shape(multiply): (1 6815 100 9)
D Tensor @Mul_170_5:out0 type: float32
D Process Conv_171_4 ...
D RKNN output shape(convolution): (1 6815 100 64)
D Tensor @Conv_171_4:out0 type: float32
D Process BatchNormalization_172_3 ...
D RKNN output shape(batchnormalize): (1 6815 100 64)
D Tensor @BatchNormalization_172_3:out0 type: float32
D Process Relu_173_2 ...
D RKNN output shape(relu): (1 6815 100 64)
D Tensor @Relu_173_2:out0 type: float32
D Process Conv_174_1 ...
D RKNN output shape(convolution): (1 6815 67 64)
D Tensor @Conv_174_1:out0 type: float32
D Process attach_Conv_174/out0_0 ...
D RKNN output shape(output): (1 6815 67 64)
D Tensor @attach_Conv_174/out0_0:out0 type: float32
I Build torch-jit-export complete.
I Initialzing network optimizer by /usr/local/lib/python3.6/dist-packages/rknn/config/npu_config/LION ...
I Start T2C Switcher...
D Optimizing network with broadcast_op, t2c_fc
D convert ReduceSum_160_14(reducesum) axes [2] to [3]
D convert Concat_168_8(concat) axis 3 to 1
D convert Concat_159_15(concat) axis 3 to 1
D convert Concat_167_7(concat) axis 3 to 1
D convert Mul_170_5(multiply) axis 3 to 1
D convert Concat_169_6(concat) axis 3 to 1
D insert permute Div_163_12_RKNN_mark_perm_25 before Div_163_12
D remove permute Div_163_12_RKNN_mark_perm_24
D remove permute Div_163_12_RKNN_mark_perm_25
I End T2C Switcher...
D Optimizing network with conv_1xn_transform, proposal_opt, c2drv_convert_axis, c2drv_convert_shape, c2drv_convert_array, c2drv_cast_dtype, c2drv_trans_data
I Building data ...
I Packing data ...
D Packing BatchNormalization_172_3 ...
D Packing Conv_171_4 ...
D Packing Conv_174_1 ...
D output tensor id = 0, name = Conv_174/out0_0
D input tensor id = 1, name = pillar_x_16
D input tensor id = 2, name = pillar_y_17
D input tensor id = 3, name = pillar_z_18
D input tensor id = 4, name = pillar_i_19
D input tensor id = 5, name = num_points_per_pillar_20
D input tensor id = 6, name = x_sub_shaped_21
D input tensor id = 7, name = y_sub_shaped_22
D input tensor id = 8, name = mask_23
I Build config finished.
--> Export RKNN model
done

上面是日志，好像没有什么异常

**Comment by 0x6c0x62** [comment]
转换出来的模型，最后输出大小不一样。原始模型是1x64x6815x1，转换后变成了67x6815x64x1
转换之前
![1](https://user-images.githubusercontent.com/24402863/133362088-47745a07-6f9f-422a-bc27-5536c1b4aa2d.png)
转换之后
<img width="565" alt="2" src="https://user-images.githubusercontent.com/24402863/133362111-1d3d9972-da38-4549-ac23-8fe9f5a39b1c.png">

**Comment by 0x6c0x62** [comment]
<img width="1439" alt="3" src="https://user-images.githubusercontent.com/24402863/133377854-0887d783-9d3c-4ebe-9011-82e4fca422b3.png">
这个地方好像转换之后不对了

**Comment by eRaul** [comment]
你使用的是什么板子？可以串口到板子上，设置一个环境变量，再重新跑你的模型，最后把板子上的日志也抓出来看下：export RKNN_LOG_LEVEL=5

**Comment by 0x6c0x62** [comment]
不是运行的时候出的问题，是模型转换的时候嘛，网络就已经不对了，20M的模型转出来不量化只有200多K，量化只有4K，而且看网络的输出shape也不对

**Comment by eRaul** [comment]
> 不是运行的时候出的问题，是模型转换的时候嘛，网络就已经不对了，20M的模型转出来不量化只有200多K，量化只有4K，而且看网络的输出shape也不对

通过板子的日志，可以确认是不是这个dilation conv的问题，如果是，我们构造个复现case，修了就好了。如果还有其他问题，我们通过板子上的日志，可以进一步分析。

**Comment by 0x6c0x62** [comment]
> > 不是运行的时候出的问题，是模型转换的时候嘛，网络就已经不对了，20M的模型转出来不量化只有200多K，量化只有4K，而且看网络的输出shape也不对
> 
> 通过板子的日志，可以确认是不是这个dilation conv的问题，如果是，我们构造个复现case，修了就好了。如果还有其他问题，我们通过板子上的日志，可以进一步分析。

我们这边改了网络，现在输出shape对了，但是模型还是200K，并且加载失败。我通过adb进入NPU那一端了，怎么看NPU的日志呢？
