### ISSUE TITLE
onnx模型导入成功，但是导出rknn模型失败

### ISSUE THREAD

**Issue by qq1243196045** [rockchip-linux/rknn-toolkit#98]
我的代码如下：
    onnx_model = './yolox.onnx'
    rknn_model = './yolox.rknn'
    input_size_list = [[1,3,416,416]]
    rknn = RKNN()
    rknn.config(mean_values=[256, 256, 256],std_values=[58.395,58.395,58.395])
    ret = rknn.load_onnx(model=onnx_model)

    ret = rknn.build(do_quantization=True,dataset='./dataset.txt')
    print(ret)
    # ret = rknn.export_rknn(rknn_model)
    # print("down")
结果：
Analysing : 100%|███████████████████████████████████████████████| 268/268 [00:00<00:00, 4775.95it/s]
Quantizating : 100%|█████████████████████████████████████████████| 268/268 [00:00<00:00, 820.38it/s]
I RKNN: librknnc version: 1.1.0b0 (8d7e25ad@2021-06-30T18:33:39)
I RKNN: set log level to 0
Process finished with exit code 136 (interrupted by signal 8: SIGFPE)

没有任何报错信息，但是我的程序异常终止了，并且也没有得到任何rknn模型。
我的环境：
ubuntu18.04 PC
python=3.6
torch=1.6
rknntoolkit=2-1.1.0b0
其他环境严格按照requirements.txt安装
需要其他信息可以补充
请问我该怎么做
onnx文件超过25M(33M)上传不了，我使用百度云上传了一份：链接: https://pan.baidu.com/s/1GG6aMOBwKMjZf4Gr4GvsLA  密码: efni

**Comment by eRaul** [comment]
> 我的代码如下：
> onnx_model = './yolox.onnx'
> rknn_model = './yolox.rknn'
> input_size_list = [[1,3,416,416]]
> rknn = RKNN()
> rknn.config(mean_values=[256, 256, 256],std_values=[58.395,58.395,58.395])
> ret = rknn.load_onnx(model=onnx_model)
> 
> ```
> ret = rknn.build(do_quantization=True,dataset='./dataset.txt')
> print(ret)
> # ret = rknn.export_rknn(rknn_model)
> # print("down")
> ```
> 
> 结果：
> Analysing : 100%|███████████████████████████████████████████████| 268/268 [00:00<00:00, 4775.95it/s]
> Quantizating : 100%|█████████████████████████████████████████████| 268/268 [00:00<00:00, 820.38it/s]
> I RKNN: librknnc version: 1.1.0b0 (8d7e25ad@2021-06-30T18:33:39)
> I RKNN: set log level to 0
> Process finished with exit code 136 (interrupted by signal 8: SIGFPE)
> 
> 没有任何报错信息，但是我的程序异常终止了，并且也没有得到任何rknn模型。
> 我的环境：
> ubuntu18.04 PC
> python=3.6
> torch=1.6
> rknntoolkit=2-1.1.0b0
> 其他环境严格按照requirements.txt安装
> 需要其他信息可以补充
> 请问我该怎么做
> onnx文件超过25M(33M)上传不了，我使用百度云上传了一份：链接: https://pan.baidu.com/s/1GG6aMOBwKMjZf4Gr4GvsLA 密码: efni

rknn toolkit2请移步这个工程：https://github.com/rockchip-linux/rknn-toolkit2
